// Original Academic Writing Task 1 prompts (IELTS-style, never copied).

import type { WritingPrompt } from "@/types/ielts";
import { academicTask1, TASK1_STANDARD_INSTRUCTION, TASK1_PROCESS_INSTRUCTION } from "./helpers";

const V = TASK1_STANDARD_INSTRUCTION;
const P = TASK1_PROCESS_INSTRUCTION;

export const academicTask1Prompts: WritingPrompt[] = [
  // ---- Existing prompts (annotated) ----
  academicTask1("acad-t1-line", "Internet users by age group (line graph)",
    `The line graph below shows the percentage of people in three age groups who used the internet in a European country between 2000 and 2020. ${V}`,
    { visualType: "line graph", visualDescription: "Three lines (16-24, 25-54, 55+). 16-24 rises from 40% to nearly 100% by 2010 and stays flat. 25-54 rises steadily from 25% to 95%. 55+ starts at 5%, stays low until 2010, then rises sharply to 60% by 2020." },
    "line"),
  academicTask1("acad-t1-bar", "Household energy consumption (bar chart)",
    `The bar chart below shows the average monthly energy consumption in kilowatt-hours for five household activities in 2010 and 2020. ${V}`,
    { visualType: "bar chart", visualDescription: "Five bar pairs (2010 vs 2020): heating 500→380, cooling 120→210, lighting 80→60, appliances 200→260, water heating 150→170." },
    "bar"),
  academicTask1("acad-t1-process", "Recycling plastic bottles (process)",
    `The diagram below shows the process by which plastic bottles are recycled. ${P}`,
    { visualType: "process diagram", visualDescription: "Steps: 1) bottles collected from homes, 2) sorted by type at a facility, 3) cleaned and crushed into flakes, 4) flakes melted into pellets, 5) pellets moulded into new products, 6) products sold and used again." },
    "process"),
  academicTask1("acad-t1-map", "Town centre redevelopment (maps)",
    `The maps below show the centre of a small town in 2000 and the proposed redevelopment for 2025. ${V}`,
    { visualType: "maps", visualDescription: "2000: main road, small shops, a car park, an old factory. 2025 plan: pedestrian zone, shopping centre, park, new bus station replacing the car park, factory converted into apartments." },
    "map"),
  academicTask1("acad-t1-pie", "Government spending (pie charts)",
    `The pie charts below show how a national government spent its budget in two different years. ${V}`,
    { visualType: "pie chart", visualDescription: "2000: education 35%, health 30%, defence 20%, transport 10%, other 5%. 2020: health 40%, education 25%, defence 15%, transport 12%, other 8%." },
    "pie"),
  academicTask1("acad-t1-table", "Rail passengers (table)",
    `The table below shows the number of rail passengers (in millions) in four regions in 2010 and 2020. ${V}`,
    { visualType: "table", dataTable: { columns: ["Region", "2010", "2020"], rows: [["North", "42", "58"], ["South", "65", "61"], ["East", "18", "34"], ["West", "29", "47"]] } },
    "table"),
  academicTask1("acad-t1-mixed", "Energy mix (mixed chart)",
    `The bar chart below shows electricity generation by source in a country, and the table shows average household electricity prices over the same period. ${V}`,
    { visualType: "mixed (bar + table)", visualDescription: "Generation (GWh): coal 320→210, gas 250→180, nuclear 150→160, renewables 60→220. Price (cents/kWh): 2010 12.5, 2015 15.0, 2020 18.5." },
    "mixed"),
  academicTask1("acad-t1-process-2", "Coffee production (process)",
    `The diagram below shows how coffee is produced from beans to cup. ${P}`,
    { visualType: "process diagram", visualDescription: "Steps: cherries picked by hand → sorted and washed → dried in the sun → hulled to remove outer layers → beans roasted → ground → brewed with hot water → served." },
    "process"),
  academicTask1("acad-t1-map-2", "Campus library (maps)",
    `The maps below show the ground floor of a university library before and after renovation. ${V}`,
    { visualType: "maps", visualDescription: "Before: entrance, issue desk, bookshelves, small reading area. After: self-service machines, larger computer zone, quiet study rooms, cafe replacing part of the bookshelves." },
    "map"),
  academicTask1("acad-t1-bar-2", "Commuting modes (bar chart)",
    `The bar chart below shows the percentage of workers using different modes of transport to commute in a city in 2000 and 2020. ${V}`,
    { visualType: "bar chart", visualDescription: "Car 65→45, bus 20→25, train 8→18, bicycle 4→9, walk 3→3 (percent)." },
    "bar"),

  // ---- New prompts ----
  academicTask1("acad-t1-line-2", "Cinema and streaming subscriptions (line graph)",
    `The line graph below shows the number of cinema tickets sold and the number of streaming subscriptions in a country between 2010 and 2020. ${V}`,
    { visualType: "line graph", visualDescription: "Cinema tickets (millions): 2010 120, 2012 125, 2014 118, 2016 108, 2018 95, 2020 70. Streaming subscriptions (millions): 2010 5, 2012 15, 2014 35, 2016 60, 2018 82, 2020 95." },
    "line"),
  academicTask1("acad-t1-line-3", "Unemployment rates by region (line graph)",
    `The line graph below shows unemployment rates in three regions of a country from 2005 to 2020. ${V}`,
    { visualType: "line graph", visualDescription: "North: 8% in 2005, falls to 4% by 2012, then fluctuates between 4% and 5%. South: steady 6% until 2010, rises to 11% by 2015, falls to 9%. East: 12% in 2005, declines steadily to 5% by 2020." },
    "line"),
  academicTask1("acad-t1-line-4", "Fish and meat consumption (line graph)",
    `The line graph below shows the average weekly consumption of fish and red meat, in grams per person, in a country between 1980 and 2020. ${V}`,
    { visualType: "line graph", visualDescription: "Red meat: 1980 900g, declines steadily to 550g by 2020. Fish: 1980 200g, rises slowly to 280g by 2005, then accelerates to 420g by 2020. Red meat consumption remains higher throughout the period, although the gap narrows substantially." },
    "line"),
  academicTask1("acad-t1-line-5", "Smartphone sales by brand (line graph)",
    `The line graph below shows annual smartphone sales, in millions of units, for four brands between 2015 and 2020. ${V}`,
    { visualType: "line graph", visualDescription: "Brand A: 40→85 steady rise. Brand B: 60→70, peaks at 75 in 2017. Brand C: 20→10 decline. Brand D: 5→35, accelerating from 2018." },
    "line"),
  academicTask1("acad-t1-bar-3", "Sports participation by age (bar chart)",
    `The bar chart below shows the percentage of people in four age groups who regularly take part in sport in a city in 2022. ${V}`,
    { visualType: "bar chart", visualDescription: "16-24: 68%, 25-39: 52%, 40-59: 38%, 60+: 24%." },
    "bar"),
  academicTask1("acad-t1-bar-4", "Hotel guest satisfaction (bar chart)",
    `The bar chart below shows the percentage of hotel guests satisfied with five aspects of their stay in 2018 and 2022. ${V}`,
    { visualType: "bar chart", visualDescription: "Cleanliness 85→92, food 70→68, service 75→80, location 88→90, value for money 65→60." },
    "bar"),
  academicTask1("acad-t1-bar-5", "Renewable energy capacity by country (bar chart)",
    `The bar chart below shows installed renewable energy capacity, in gigawatts, in five countries in 2015 and 2021. ${V}`,
    { visualType: "bar chart", visualDescription: "Country A 120→210, B 80→95, C 45→70, D 30→52, E 10→22." },
    "bar"),
  academicTask1("acad-t1-pie-2", "Household water use (pie charts)",
    `The pie charts below show how household water is used in two countries in 2020. ${V}`,
    { visualType: "pie chart", visualDescription: "Country A: toilets 30%, showers 28%, washing 22%, garden 12%, kitchen 8%. Country B: garden 45%, showers 25%, washing 15%, toilets 10%, kitchen 5%." },
    "pie"),
  academicTask1("acad-t1-pie-3", "Sources of electricity (pie chart)",
    `The pie chart below shows the sources of electricity generation in a country in 2020. ${V}`,
    { visualType: "pie chart", visualDescription: "Gas 38%, renewables 30%, nuclear 17%, coal 12%, other 3% (sums to 100%)." },
    "pie"),
  academicTask1("acad-t1-pie-4", "Reasons for cycling to work (pie chart)",
    `The pie chart below shows the main reasons given by commuters for cycling to work in a city in 2021. ${V}`,
    { visualType: "pie chart", visualDescription: "Health 35%, cost 25%, environment 20%, speed 12%, other 8% (sums to 100%)." },
    "pie"),
  academicTask1("acad-t1-table-2", "Internet access in schools (table)",
    `The table below shows the percentage of schools with internet access in four regions in 2005, 2012 and 2019. ${V}`,
    { visualType: "table", dataTable: { columns: ["Region", "2005", "2012", "2019"], rows: [["North", "62", "85", "98"], ["South", "38", "64", "90"], ["East", "20", "48", "76"], ["West", "45", "70", "93"]] } },
    "table"),
  academicTask1("acad-t1-table-3", "Average working hours (table)",
    `The table below shows the average weekly working hours in five sectors in two countries in 2020. ${V}`,
    { visualType: "table", dataTable: { columns: ["Sector", "Country A", "Country B"], rows: [["Manufacturing", "39", "44"], ["Retail", "31", "28"], ["Healthcare", "36", "40"], ["Education", "33", "30"], ["Construction", "41", "46"]] } },
    "table"),
  academicTask1("acad-t1-table-4", "International student numbers (table)",
    `The table below shows the number of international students at a university in 2010 and 2020, by region of origin. ${V}`,
    { visualType: "table", dataTable: { columns: ["Region", "2010", "2020"], rows: [["Asia", "3200", "6100"], ["Europe", "2100", "2400"], ["Africa", "900", "1800"], ["Americas", "1100", "1300"]] } },
    "table"),
  academicTask1("acad-t1-process-3", "Paper production (process)",
    `The diagram below shows how paper is produced from recycled material. ${P}`,
    { visualType: "process diagram", visualDescription: "Steps: waste paper collected → sorted and shredded → mixed with water into pulp → cleaned and de-inked → spread and pressed into sheets → dried on heated rollers → rolled and cut for sale." },
    "process"),
  academicTask1("acad-t1-process-4", "Water cycle in a city (natural process)",
    `The diagram below shows the natural water cycle in an urban area. ${P}`,
    { visualType: "process diagram", visualDescription: "Steps: rainwater falls on roofs and streets → runs into drains → enters treatment plant → cleaned water released into river → evaporates into clouds → falls again as rain." },
    "process"),
  academicTask1("acad-t1-map-3", "Coastal village development (maps)",
    `The maps below show a coastal village in 1990 and in 2020. ${V}`,
    { visualType: "maps", visualDescription: "1990: fishing harbour, twenty houses, one shop, a school. 2020: harbour enlarged into a marina, holiday apartments replace some houses, three restaurants added, new promenade, school relocated inland." },
    "map"),
  academicTask1("acad-t1-map-4", "Airport terminal redesign (maps)",
    `The maps below show the ground floor of an airport terminal before and after a major redesign. ${V}`,
    { visualType: "maps", visualDescription: "Before: single check-in hall, small departure lounge, two shops. After: self-service check-in zone, expanded security area, six shops and a food court, larger departure lounge." },
    "map"),
  academicTask1("acad-t1-mixed-2", "Tourism arrivals and spending (mixed)",
    `The line graph below shows the number of international tourist arrivals in a country, and the table shows average spending per visitor, between 2010 and 2020. ${V}`,
    { visualType: "mixed (line + table)", visualDescription: "Arrivals (millions): 2010 12, 2014 18, 2018 24, 2020 9. Spending per visitor ($): 2010 720, 2014 810, 2018 940, 2020 1050." },
    "mixed"),
  academicTask1("acad-t1-mixed-3", "Crop production and farmland (mixed)",
    `The bar chart below shows wheat production in a region, and the pie chart shows the use of its farmland, in 2020. ${V}`,
    { visualType: "mixed (bar + pie)", visualDescription: "Wheat production (thousand tonnes): 2015 320, 2020 390. Farmland use: wheat 45%, vegetables 20%, livestock 18%, fruit 10%, other 7% (sums to 100%)." },
    "mixed"),
  academicTask1("acad-t1-mixed-4", "Student numbers by subject (mixed)",
    `The table below shows university enrolment by subject in 2010, and the bar chart shows the same subjects in 2020. ${V}`,
    { visualType: "mixed (table + bar)", visualDescription: "2010 (table, thousands): Business 45, Engineering 30, Arts 25, Sciences 28. 2020 (bar): Business 58, Engineering 42, Arts 22, Sciences 41." },
    "mixed"),
];
