// Original General Training Writing Task 1 (letters). All original scenarios.

import type { WritingPrompt } from "@/types/ielts";
import { generalTask1 } from "./helpers";

export const generalTask1Prompts: WritingPrompt[] = [
  // ---- Existing prompts (annotated) ----
  generalTask1("gen-t1-complaint", "Complaint letter",
    "You recently bought a laptop online, but it arrived damaged. Write a letter to the store. In your letter: describe the problem with the laptop, explain how this has affected you, say what you would like the store to do.",
    "formal", "complaint"),
  generalTask1("gen-t1-invite", "Invitation letter (informal)",
    "Your friend is visiting your city next month. Write a letter to invite them to stay with you. In your letter: suggest some activities you could do together, describe where you live, offer to help them plan their visit.",
    "informal", "invitation"),
  generalTask1("gen-t1-request", "Request for information (formal)",
    "You would like to enrol in a language course at a college in another city. Write a letter to the admissions office. In your letter: explain why you want to take the course, ask about course dates and fees, ask about accommodation options.",
    "formal", "request"),
  generalTask1("gen-t1-apology", "Apology letter",
    "You missed a meeting with a colleague because of an unexpected emergency. Write a letter to apologise. In your letter: explain why you missed the meeting, say how you plan to make up for it, suggest a new time to meet.",
    "semi_formal", "apology"),
  generalTask1("gen-t1-application", "Job application letter",
    "You have seen a job advertisement for a part-time position at a local museum. Write a letter to apply. In your letter: explain why you are interested in the job, describe your relevant experience, say when you are available for an interview.",
    "formal", "application"),
  generalTask1("gen-t1-recommend", "Recommendation letter",
    "A friend has asked you to recommend a place for a family holiday. Write a letter to your friend. In your letter: recommend a place you know well, describe what the family can do there, explain why it is suitable for a family.",
    "informal", "recommendation"),
  generalTask1("gen-t1-thanks", "Thank-you letter",
    "You recently stayed with a host family during a study trip. Write a letter to thank them. In your letter: say what you enjoyed about your stay, mention something you learned from them, invite them to visit you.",
    "informal", "thanks"),
  generalTask1("gen-t1-info", "Letter asking for information",
    "You are moving to a new city and need information about renting a flat. Write a letter to a local letting agency. In your letter: describe the type of flat you need, ask about rental costs and contracts, ask about the best areas to live.",
    "formal", "request"),

  // ---- New prompts ----
  generalTask1("gen-t1-formal-complaint-02", "Complaint about a faulty appliance",
    "You bought a washing machine two months ago, and it has stopped working twice. Write a letter to the store manager. In your letter: describe the faults, explain the inconvenience this has caused, say what you expect the store to do.",
    "formal", "complaint"),
  generalTask1("gen-t1-formal-enquiry-02", "Enquiry about a training course",
    "You have seen an advertisement for a professional training course that interests you. Write a letter to the training provider. In your letter: explain why you are interested in the course, ask about entry requirements and fees, ask how to apply.",
    "formal", "enquiry"),
  generalTask1("gen-t1-formal-request-02", "Request to change a booking",
    "You have booked a hotel room for a business trip, but your plans have changed. Write a letter to the hotel. In your letter: give the details of your booking, explain the change to your plans, ask for the booking to be changed or cancelled.",
    "formal", "request"),
  generalTask1("gen-t1-formal-explanation-01", "Explanation to an insurance company",
    "Your luggage was damaged during a recent flight. Write a letter to the airline's customer service department. In your letter: describe the damage, explain the value of the items, say what compensation you are requesting.",
    "formal", "explanation"),
  generalTask1("gen-t1-formal-feedback-01", "Feedback about poor service",
    "You recently had a meal at a restaurant where the service was unsatisfactory. Write a letter to the restaurant manager. In your letter: describe what went wrong, explain how it affected your evening, suggest how the restaurant could improve.",
    "formal", "feedback"),
  generalTask1("gen-t1-semi-arrangement-01", "Arranging a work handover",
    "You are leaving your job and need to explain your tasks to a colleague. Write a letter to that colleague. In your letter: describe the main tasks that need to be handed over, explain which tasks are urgent, suggest a time to meet and discuss them.",
    "semi_formal", "arrangement"),
  generalTask1("gen-t1-semi-reschedule-01", "Rescheduling an appointment",
    "You have an appointment with a doctor next week, but you can no longer attend. Write a letter to the clinic. In your letter: give the details of your appointment, explain why you cannot attend, ask for an alternative date or time.",
    "semi_formal", "rescheduling"),
  generalTask1("gen-t1-semi-thanks-02", "Thanking a colleague",
    "A colleague helped you finish an important project before a deadline. Write a letter to thank them. In your letter: explain what they helped you with, describe how their help made a difference, offer to return the favour in the future.",
    "semi_formal", "thanks"),
  generalTask1("gen-t1-semi-apology-02", "Apology for missing an event",
    "You agreed to attend a friend's birthday celebration, but you were unable to go. Write a letter to apologise. In your letter: explain why you could not attend, say how sorry you are to have missed it, suggest meeting up soon to celebrate together.",
    "semi_formal", "apology"),
  generalTask1("gen-t1-semi-request-02", "Requesting time off",
    "You would like to take a week off work for a family event. Write a letter to your manager. In your letter: explain the reason for your request, say when you would like the time off, describe how your work will be covered.",
    "semi_formal", "request"),
  generalTask1("gen-t1-semi-advice-01", "Advice for a new neighbour",
    "A new family has moved into the house next door. Write a letter to welcome them and offer advice. In your letter: welcome them to the neighbourhood, tell them about local services and facilities, offer practical help with settling in.",
    "semi_formal", "advice"),
  generalTask1("gen-t1-semi-lost-01", "Reporting lost property",
    "You left your bag on a train last week and have not been able to find it. Write a letter to the train company's lost property office. In your letter: describe the bag and where you left it, list the important items inside, explain how to contact you if it is found.",
    "semi_formal", "lost property"),
  generalTask1("gen-t1-informal-advice-02", "Advice about studying abroad",
    "A close friend is planning to study abroad and has asked for your advice. Write a letter to your friend. In your letter: give advice about choosing a course, suggest how to prepare for living in another country, offer your help.",
    "informal", "advice"),
  generalTask1("gen-t1-informal-invite-02", "Invitation to a family event",
    "Your family is organising a special celebration, and you want to invite a friend who lives in another town. Write a letter to invite them. In your letter: describe the celebration, explain who will be there, suggest how they could travel and stay.",
    "informal", "invitation"),
  generalTask1("gen-t1-informal-thanks-02", "Thanks for a gift",
    "A friend sent you a gift for your birthday. Write a letter to thank them. In your letter: say how you felt when you received it, describe how you have used or displayed the gift, mention when you might see them next.",
    "informal", "thanks"),
  generalTask1("gen-t1-informal-update-01", "Updating a friend on a new job",
    "You have recently started a new job in a different city. Write a letter to a friend you have not contacted for a while. In your letter: describe your new job, explain what you like about the new city, invite your friend to visit.",
    "informal", "arrangement"),
  generalTask1("gen-t1-informal-plan-01", "Planning a group outing",
    "You are organising a day out for a group of friends. Write a letter to one of the friends to discuss the plans. In your letter: suggest a place and a date, describe what you have planned, ask for their ideas and preferences.",
    "informal", "arrangement"),
];

export type { WritingPrompt };
