// Original IELTS Writing Task 2 prompts with machine-readable subtypes.

import type { WritingPrompt } from "@/types/ielts";
import { task2 } from "./helpers";

export const task2Prompts: WritingPrompt[] = [
  // ---- Existing prompts (annotated) ----
  task2("t2-agree", "academic", "Agree/disagree: technology in education",
    "Some people believe that computers and the internet will soon replace teachers in the classroom. To what extent do you agree or disagree?", "agree_disagree"),
  task2("t2-both-views", "academic", "Discuss both views: remote work",
    "Some people think that working from home benefits employees more than employers, while others believe the opposite. Discuss both views and give your own opinion.", "discuss_both_views"),
  task2("t2-problem-solution", "academic", "Problem/solution: urban congestion",
    "Traffic congestion is a growing problem in many large cities. What problems does this cause, and what measures could be taken to solve them?", "problem_solution"),
  task2("t2-adv-disadv", "general", "Advantages/disadvantages: tourism",
    "International tourism has become a huge industry, but it also creates problems for local communities. Do the advantages of international tourism outweigh the disadvantages?", "outweigh"),
  task2("t2-positive-negative", "general", "Positive/negative: social media",
    "Social media has changed the way people communicate with each other. Is this a positive or negative development?", "positive_negative"),
  task2("t2-two-part", "academic", "Two-part: childhood obesity",
    "In many countries, the number of children who are overweight is increasing. Why is this happening? What can be done to solve this problem?", "causes_solutions"),
  task2("t2-agree-2", "academic", "Agree/disagree: university education",
    "Some people believe that university education should be free for everyone. To what extent do you agree or disagree?", "agree_disagree"),
  task2("t2-both-2", "academic", "Discuss both views: advertising",
    "Some people think advertising is a harmless form of entertainment, while others believe it manipulates people into buying things they do not need. Discuss both views and give your own opinion.", "discuss_both_views"),
  task2("t2-problem-2", "general", "Problem/solution: plastic waste",
    "Plastic waste is damaging the environment in many countries. What problems does plastic waste cause, and what measures can be taken to reduce it?", "problem_solution"),
  task2("t2-adv-2", "general", "Advantages/disadvantages: online learning",
    "More and more students are choosing to study online rather than attend classes in person. Do the advantages of this trend outweigh the disadvantages?", "outweigh"),
  task2("t2-two-part-2", "academic", "Two-part: ageing population",
    "In many developed countries, the average age of the population is increasing. What problems does this cause for individuals and society? What can be done to deal with these problems?", "problem_solution"),
  task2("t2-agree-3", "general", "Agree/disagree: city living",
    "Some people believe that living in a large city has more disadvantages than advantages. To what extent do you agree or disagree?", "agree_disagree"),
  task2("t2-both-3", "academic", "Discuss both views: space exploration",
    "Some people believe space exploration is a waste of money, while others think it is essential for humanity's future. Discuss both views and give your own opinion.", "discuss_both_views"),
  task2("t2-problem-3", "academic", "Problem/solution: food waste",
    "A large amount of food is wasted every day in many countries. Why is this happening, and what can individuals do to reduce food waste?", "causes_solutions"),

  // ---- New prompts: agree / disagree (+7) ----
  task2("t2-agree-4", "academic", "Agree/disagree: school uniforms",
    "Some people believe that requiring school uniforms improves discipline and reduces social pressure on students. To what extent do you agree or disagree?", "agree_disagree"),
  task2("t2-agree-5", "general", "Agree/disagree: saving money",
    "Some people think it is better to enjoy your money while you can, rather than save it for the future. To what extent do you agree or disagree?", "agree_disagree"),
  task2("t2-agree-6", "academic", "Agree/disagree: stricter punishments for drivers",
    "Some people believe that stricter punishments are the only way to reduce traffic accidents. To what extent do you agree or disagree?", "agree_disagree"),
  task2("t2-agree-7", "general", "Agree/disagree: unpaid community work for teenagers",
    "Some people think that teenagers should be required to do unpaid work in their local communities. To what extent do you agree or disagree?", "agree_disagree"),
  task2("t2-agree-8", "academic", "Agree/disagree: the value of art",
    "Some people argue that government money spent on the arts is wasted, while that money could be better used elsewhere. To what extent do you agree or disagree?", "agree_disagree"),
  task2("t2-agree-9", "general", "Agree/disagree: owning a home",
    "In some countries, owning a home is considered more important than renting one. To what extent do you agree or disagree with this view?", "agree_disagree"),
  task2("t2-agree-10", "academic", "Agree/disagree: advertising to children",
    "Some people believe that advertising aimed at children should be banned. To what extent do you agree or disagree?", "agree_disagree"),

  // ---- New prompts: discuss both views (+6) ----
  task2("t2-discuss-1", "academic", "Discuss both views: animal testing",
    "Some people think that testing new medicines on animals is necessary, while others believe it is cruel and should be stopped. Discuss both views and give your own opinion.", "discuss_both_views"),
  task2("t2-discuss-2", "general", "Discuss both views: e-books vs printed books",
    "Some people believe that printed books will soon disappear because of e-books, while others think printed books will always have a place. Discuss both views and give your own opinion.", "discuss_both_views"),
  task2("t2-discuss-3", "academic", "Discuss both views: young vs old in the workplace",
    "Some employers prefer to hire younger workers, while others value the experience of older employees. Discuss both views and give your own opinion.", "discuss_both_views"),
  task2("t2-discuss-4", "general", "Discuss both views: children and television",
    "Some people think television is a useful educational tool for children, while others believe it does more harm than good. Discuss both views and give your own opinion.", "discuss_both_views"),
  task2("t2-discuss-5", "academic", "Discuss both views: fast food",
    "Some people think fast food has made modern life more convenient, while others argue it has damaged people's health and traditional food culture. Discuss both views and give your own opinion.", "discuss_both_views"),
  task2("t2-discuss-6", "general", "Discuss both views: working part-time while studying",
    "Some students prefer to work part-time while they study, while others believe students should focus only on their education. Discuss both views and give your own opinion.", "discuss_both_views"),

  // ---- New prompts: advantages / disadvantages (+9) ----
  task2("t2-adv-3", "academic", "Advantages/disadvantages: living alone",
    "In many countries, more people are choosing to live alone than at any time in the past. What are the advantages and disadvantages of this trend?", "advantages_disadvantages"),
  task2("t2-adv-4", "general", "Advantages/disadvantages: working from a café",
    "An increasing number of people work from cafés and other public places. What are the advantages and disadvantages of this way of working?", "advantages_disadvantages"),
  task2("t2-adv-5", "academic", "Advantages/disadvantages: shopping online",
    "Online shopping has become extremely popular in recent years. What are the advantages and disadvantages of shopping online compared with shopping in stores?", "advantages_disadvantages"),
  task2("t2-adv-6", "general", "Advantages/disadvantages: owning a car",
    "In many cities, owning a car is seen as essential, while in others it is becoming unnecessary. What are the advantages and disadvantages of owning a car?", "advantages_disadvantages"),
  task2("t2-adv-7", "academic", "Advantages/disadvantages: studying a foreign language at primary school",
    "Some countries teach foreign languages to primary school children, while others wait until secondary school. What are the advantages and disadvantages of starting language learning early?", "advantages_disadvantages"),
  task2("t2-adv-8", "general", "Advantages/disadvantages: living with extended family",
    "In some cultures, several generations of a family live together in one home. What are the advantages and disadvantages of this arrangement?", "advantages_disadvantages"),
  task2("t2-adv-9", "academic", "Advantages/disadvantages: freelance work",
    "A growing number of people are choosing to work as freelancers rather than full-time employees. What are the advantages and disadvantages of freelance work?", "advantages_disadvantages"),
  task2("t2-adv-10", "general", "Advantages/disadvantages: cycling in cities",
    "Many cities are encouraging people to cycle instead of driving. What are the advantages and disadvantages of cycling as a form of urban transport?", "advantages_disadvantages"),
  task2("t2-adv-11", "academic", "Advantages/disadvantages: international exchange programmes",
    "Many universities encourage students to spend a year studying in another country. What are the advantages and disadvantages of such exchange programmes?", "advantages_disadvantages"),

  // ---- New prompts: outweigh (+5) ----
  task2("t2-outweigh-1", "academic", "Outweigh: driverless cars",
    "In the future, most vehicles are likely to be driverless. Do the advantages of driverless cars outweigh the disadvantages?", "outweigh"),
  task2("t2-outweigh-2", "general", "Outweigh: high-rise living",
    "In many cities, new housing is being built in tall apartment blocks. Do the advantages of living in high-rise buildings outweigh the disadvantages?", "outweigh"),
  task2("t2-outweigh-3", "academic", "Outweigh: tourism in developing countries",
    "Tourism can bring income to poorer countries, but it can also cause environmental and cultural damage. Do the advantages of tourism in developing countries outweigh the disadvantages?", "outweigh"),
  task2("t2-outweigh-4", "general", "Outweigh: automation in the home",
    "More and more household tasks are being automated by smart devices. Do the advantages of this trend outweigh the disadvantages?", "outweigh"),
  task2("t2-outweigh-5", "academic", "Outweigh: working longer hours",
    "In some countries, employees are expected to work longer hours than in the past. Do the advantages of working longer hours outweigh the disadvantages?", "outweigh"),

  // ---- New prompts: positive / negative (+6) ----
  task2("t2-posneg-2", "academic", "Positive/negative: smartphones",
    "Smartphones have become an essential part of daily life for billions of people. Is this a positive or negative development?", "positive_negative"),
  task2("t2-posneg-3", "general", "Positive/negative: online reviews",
    "People now rely heavily on online reviews when choosing restaurants, hotels and services. Is this a positive or negative development?", "positive_negative"),
  task2("t2-posneg-4", "academic", "Positive/negative: 24-hour shopping",
    "In many cities, shops and supermarkets are now open twenty-four hours a day. Is this a positive or negative development?", "positive_negative"),
  task2("t2-posneg-5", "general", "Positive/negative: children and tablets",
    "Very young children are now spending a significant amount of time using tablets and other screens. Is this a positive or negative development?", "positive_negative"),
  task2("t2-posneg-6", "academic", "Positive/negative: cashless payments",
    "In some countries, cash is disappearing as people pay for almost everything electronically. Is this a positive or negative development?", "positive_negative"),
  task2("t2-posneg-7", "general", "Positive/negative: short-term rentals",
    "Many homeowners now rent out their properties to tourists for short stays. Is this a positive or negative development for local communities?", "positive_negative"),

  // ---- New prompts: problem / solution (+5) ----
  task2("t2-problem-4", "academic", "Problem/solution: noise pollution",
    "Noise pollution is becoming a serious problem in many cities. What problems does it cause, and what can be done to reduce it?", "problem_solution"),
  task2("t2-problem-5", "general", "Problem/solution: loneliness in old age",
    "Many elderly people experience loneliness in modern society. What problems does this cause, and what can be done to help them?", "problem_solution"),
  task2("t2-problem-6", "academic", "Problem/solution: water shortages",
    "Many parts of the world are experiencing serious water shortages. What problems does this cause, and what measures can governments take to address them?", "problem_solution"),
  task2("t2-problem-7", "general", "Problem/solution: stress at work",
    "Work-related stress has become increasingly common. What problems does this cause for workers and employers, and how can it be reduced?", "problem_solution"),
  task2("t2-problem-8", "academic", "Problem/solution: rural depopulation",
    "In many countries, young people are leaving rural areas to live in cities. What problems does this cause, and what can be done to encourage people to stay in the countryside?", "problem_solution"),

  // ---- New prompts: causes / effects (+3) ----
  task2("t2-causes-effects-1", "academic", "Causes/effects: declining reading habits",
    "In many countries, young people are reading fewer books than previous generations. What are the causes of this trend, and what effects might it have on society?", "causes_effects"),
  task2("t2-causes-effects-2", "general", "Causes/effects: smaller family sizes",
    "In many countries, families are becoming smaller than in the past. What are the causes of this change, and what effects does it have on society?", "causes_effects"),
  task2("t2-causes-effects-3", "academic", "Causes/effects: loss of local shops",
    "Small local shops are closing in many towns as large supermarkets and online retailers expand. What are the causes of this trend, and what are its effects on communities?", "causes_effects"),

  // ---- New prompts: two-part (+5) ----
  task2("t2-two-part-3", "academic", "Two-part: technology and free time",
    "People today have more free time thanks to technology, yet many report feeling busier than ever. Why do you think this is the case? What could people do to use their free time better?", "two_part"),
  task2("t2-two-part-4", "general", "Two-part: healthy eating",
    "Many people know which foods are healthy but continue to eat unhealthily. Why is this? What can be done to encourage people to eat more healthily?", "two_part"),
  task2("t2-two-part-5", "academic", "Two-part: public transport",
    "Public transport in many cities is considered unreliable and expensive. Why is public transport failing in these places? What can governments do to improve it?", "two_part"),
  task2("t2-two-part-6", "general", "Two-part: recycling",
    "Although recycling is widely encouraged, many households still do not recycle. Why is this? What can be done to increase recycling rates?", "two_part"),
  task2("t2-two-part-7", "academic", "Two-part: music education",
    "In some schools, music lessons are being reduced in favour of more academic subjects. Why is this happening? Is this a positive development for students?", "two_part"),
  task2("t2-two-part-8", "academic", "Two-part: museum visits",
    "Many museums charge visitors an entrance fee, while others are free. Why do some museums charge while others do not? Which approach is better for the public?", "two_part"),
  task2("t2-two-part-9", "general", "Two-part: learning a musical instrument",
    "Fewer children are learning to play a musical instrument than in the past. Why is this? Should schools do more to encourage children to learn music?", "two_part"),
  task2("t2-two-part-10", "academic", "Two-part: city-centre pedestrian zones",
    "Some cities have turned their centres into pedestrian-only zones where cars are banned. Why do cities take this step? What effects does it have on residents and businesses?", "two_part"),
  task2("t2-two-part-11", "general", "Two-part: handmade goods",
    "Handmade goods are becoming more expensive and less common, while mass-produced items dominate the market. Why is this happening? Is it important to preserve traditional crafts?", "two_part"),
];

export type { WritingPrompt };
