// IELTS-oriented grammar practice exercises with explanations.

export type GrammarExerciseKind =
  | "gap_fill"
  | "sentence_choice"
  | "error_identification"
  | "correction"
  | "style_choice"
  | "punctuation";

export interface GrammarExercise {
  id: string;
  topic: string;
  sentence: string;
  // The blank is marked with ___. Correct answer fills it.
  options: string[];
  correct: number;
  explanation: string;
  errorType: string;
  // Links this exercise to a canonical Grammar lesson (Learn → Practice).
  lessonId: string;
  kind: GrammarExerciseKind;
  difficulty: 1 | 2 | 3;
}

export const grammarExercises: GrammarExercise[] = [
  {
    id: "g-sv-1",
    topic: "Subject–verb agreement",
    sentence: "The number of people using public transport ___ increased sharply.",
    options: ["have", "has", "are"],
    correct: 1,
    explanation: "'The number of…' takes a singular verb, so 'has' is correct.",
    lessonId: "gram-agreement",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "subject-verb agreement",
  },
  {
    id: "g-sv-2",
    topic: "Subject–verb agreement",
    sentence: "A number of students ___ applied for the scholarship.",
    options: ["has", "is", "have"],
    correct: 2,
    explanation: "'A number of…' takes a plural verb, so 'have' is correct.",
    lessonId: "gram-agreement",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "subject-verb agreement",
  },
  {
    id: "g-art-1",
    topic: "Articles",
    sentence: "She gave me ___ useful advice about the interview.",
    options: ["a", "an", "—"],
    correct: 2,
    explanation: "'Advice' is uncountable and takes no article.",
    lessonId: "gram-articles-countability",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "articles / countable nouns",
  },
  {
    id: "g-art-2",
    topic: "Articles",
    sentence: "___ information you provided was very helpful.",
    options: ["A", "The", "An"],
    correct: 1,
    explanation: "'The' is used because the information is specific and previously mentioned; 'a/an' cannot precede uncountable 'information'.",
    lessonId: "gram-articles-countability",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "articles",
  },
  {
    id: "g-tense-1",
    topic: "Tense consistency",
    sentence: "By the time we arrived, the meeting ___.",
    options: ["already started", "has already started", "had already started"],
    correct: 2,
    explanation: "Past perfect ('had started') is used for an action completed before another past action.",
    lessonId: "gram-tenses-conditionals",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "tense",
  },
  {
    id: "g-tense-2",
    topic: "Tense consistency",
    sentence: "Since 2015, the city ___ its public transport network.",
    options: ["expanded", "has expanded", "expands"],
    correct: 1,
    explanation: "'Since + past time' requires the present perfect ('has expanded').",
    lessonId: "gram-tenses-conditionals",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "tense",
  },
  {
    id: "g-modal-1",
    topic: "Modals",
    sentence: "Students ___ wear a uniform, but most choose to.",
    options: ["must", "don't have to", "can't"],
    correct: 1,
    explanation: "'Don't have to' expresses lack of obligation, matching 'but most choose to'.",
    lessonId: "gram-passive-modals",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "modals",
  },
  {
    id: "g-cond-1",
    topic: "Conditionals",
    sentence: "If the government ___ more in education, results would improve.",
    options: ["invests", "invested", "will invest"],
    correct: 1,
    explanation: "Second conditional (unreal present): past simple in the if-clause, 'would' in the result; 'will' never follows 'if' here.",
    lessonId: "gram-tenses-conditionals",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "conditionals",
  },
  {
    id: "g-cond-2",
    topic: "Conditionals",
    sentence: "If we had left earlier, we ___ the train.",
    options: ["would catch", "would have caught", "will catch"],
    correct: 1,
    explanation: "Third conditional (unreal past) uses 'would have + past participle'.",
    lessonId: "gram-tenses-conditionals",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "conditionals",
  },
  {
    id: "g-passive-1",
    topic: "Passive voice",
    sentence: "The bottles ___ and then transported to the factory.",
    options: ["clean", "are cleaned", "cleaned"],
    correct: 1,
    explanation: "Process descriptions use the passive: 'are cleaned'.",
    lessonId: "gram-passive-modals",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "passive voice",
  },
  {
    id: "g-rel-1",
    topic: "Relative clauses",
    sentence: "The new cycle lane, ___ opened in May, is already popular.",
    options: ["that", "which", "who"],
    correct: 1,
    explanation: "A non-defining relative clause uses 'which' (with commas), not 'that'.",
    lessonId: "gram-relative-clauses",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "relative clauses",
  },
  {
    id: "g-noun-1",
    topic: "Noun clauses",
    sentence: "___ the data shows is a clear decline in sales.",
    options: ["That", "What", "Which"],
    correct: 1,
    explanation: "'What' introduces a noun clause as the subject of the sentence.",
    lessonId: "gram-noun-clauses",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "noun clauses",
  },
  {
    id: "g-adv-1",
    topic: "Adverbial clauses",
    sentence: "Which connector explicitly expresses cause? '___ demand rose, prices increased sharply.'",
    options: ["Because", "Although", "Despite"],
    correct: 0,
    explanation: "'Because' introduces the cause stated in the first clause. 'Although' would express concession, while 'despite' cannot directly introduce the finite clause 'demand rose'.",
    lessonId: "gram-adverbial-clauses",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "adverbial clauses",
  },
  {
    id: "g-ger-1",
    topic: "Gerunds / infinitives",
    sentence: "Many people enjoy ___ in their free time.",
    options: ["to travel", "travel", "travelling"],
    correct: 2,
    explanation: "'Enjoy' is followed by a gerund ('travelling').",
    lessonId: "gram-gerunds-infinitives",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "gerunds/infinitives",
  },
  {
    id: "g-comp-1",
    topic: "Comparatives",
    sentence: "This is ___ interesting book I have ever read.",
    options: ["the most", "more", "most"],
    correct: 0,
    explanation: "Superlative with 'the most' is used for three or more items.",
    lessonId: "gram-comparisons-quantifiers",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "comparatives/superlatives",
  },
  {
    id: "g-prep-1",
    topic: "Prepositions",
    sentence: "The course focuses ___ developing practical skills.",
    options: ["in", "on", "at"],
    correct: 1,
    explanation: "'Focus on' is the correct collocation.",
    lessonId: "gram-prepositions-collocations",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "prepositions",
  },
  {
    id: "g-conj-1",
    topic: "Conjunctions",
    sentence: "Which conjunctive adverb explicitly expresses contrast? 'The project was difficult; ___, the team completed it on time.'",
    options: ["however", "therefore", "for example"],
    correct: 0,
    explanation: "'However' explicitly marks contrast between the project's difficulty and the successful on-time completion. 'Therefore' expresses result, while 'for example' introduces an example.",
    lessonId: "gram-cohesion-reference",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "conjunctions",
  },
  {
    id: "g-punc-1",
    topic: "Punctuation",
    sentence: "Which correctly uses a colon to introduce a list?",
    options: ["We need to buy three things: bread, milk and eggs.", "We need to buy three things; bread, milk and eggs.", "We need to buy three things, bread, milk and eggs."],
    correct: 0,
    explanation: "A colon introduces the list after the complete clause 'We need to buy three things'.",
    lessonId: "gram-punctuation",
    kind: "punctuation",
    difficulty: 1,
    errorType: "punctuation",
  },
  {
    id: "g-par-1",
    topic: "Parallelism",
    sentence: "The job involves planning, organising and ___ reports.",
    options: ["write", "writing", "to write"],
    correct: 1,
    explanation: "Parallel structure requires matching gerunds: planning, organising, writing.",
    lessonId: "gram-parallelism",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "parallelism",
  },
  {
    id: "g-frag-1",
    topic: "Fragments",
    sentence: "Which sentence is complete?",
    options: ["Because the cost was too high.", "The project was cancelled because the cost was too high.", "Although the cost was too high."],
    correct: 1,
    explanation: "Only the middle option has a complete independent clause.",
    lessonId: "gram-punctuation",
    kind: "sentence_choice",
    difficulty: 1,
    errorType: "fragments",
  },
  {
    id: "g-runon-1",
    topic: "Run-on sentences",
    sentence: "Which correctly avoids a comma splice?",
    options: ["The test was hard, we still passed.", "The test was hard; however, we still passed.", "The test was hard we still passed."],
    correct: 1,
    explanation: "A semicolon (or a full stop) correctly joins the two independent clauses; a comma alone creates a comma splice.",
    lessonId: "gram-punctuation",
    kind: "sentence_choice",
    difficulty: 1,
    errorType: "run-on sentences",
  },
  {
    id: "g-formal-1",
    topic: "Formal academic style",
    sentence: "Which is the most formal?",
    options: ["The government decided to cut taxes.", "The government's decision to cut taxes was widely debated.", "They decided to cut taxes, you know."],
    correct: 1,
    explanation: "Nominalisation ('the government's decision') is a feature of formal academic style.",
    lessonId: "gram-academic-style",
    kind: "style_choice",
    difficulty: 2,
    errorType: "formal style / nominalisation",
  },
  {
    id: "g-hedge-1",
    topic: "Hedging",
    sentence: "Which sentence uses appropriate hedging?",
    options: ["The policy will definitely solve every problem.", "The policy is likely to reduce some of the pressure on housing.", "The policy must end all homelessness at once."],
    correct: 1,
    explanation: "'Likely' and 'some of the pressure' hedge the claim appropriately; the others overstate.",
    lessonId: "gram-academic-style",
    kind: "style_choice",
    difficulty: 2,
    errorType: "hedging",
  },
  {
    id: "g-sv-3",
    topic: "Subject–verb agreement",
    sentence: "Neither the manager nor the employees ___ aware of the change.",
    options: ["was", "were", "is"],
    correct: 1,
    explanation: "With 'neither…nor', the verb agrees with the nearer subject ('the employees' → plural).",
    lessonId: "gram-agreement",
    kind: "gap_fill",
    difficulty: 3,
    errorType: "subject-verb agreement",
  },
  {
    id: "g-art-3",
    topic: "Articles",
    sentence: "He plays ___ important role in the community.",
    options: ["a", "an", "the"],
    correct: 1,
    explanation: "'An' precedes a vowel sound ('important').",
    lessonId: "gram-articles-countability",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "articles",
  },
  {
    id: "g-tense-3",
    topic: "Tense consistency",
    sentence: "She ___ in London since 2019.",
    options: ["lives", "has lived", "lived"],
    correct: 1,
    explanation: "Present perfect ('has lived') is used with 'since' for an action continuing to now.",
    lessonId: "gram-tenses-conditionals",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "tense",
  },
  {
    id: "g-cond-3",
    topic: "Conditionals",
    sentence: "If I had studied harder, I ___ the exam last week.",
    options: ["would pass", "would have passed", "will pass"],
    correct: 1,
    explanation: "Third conditional with a past-time anchor: past perfect in the if-clause, 'would have + past participle' in the result.",
    lessonId: "gram-tenses-conditionals",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "conditionals",
  },
  {
    id: "g-rel-2",
    topic: "Relative clauses",
    sentence: "The chart, ___ shows export data, was published last year.",
    options: ["which", "that", "who"],
    correct: 0,
    explanation: "Non-defining relative clauses use 'which' (with commas), never 'that'.",
    lessonId: "gram-relative-clauses",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "relative clauses",
  },
  {
    id: "g-pass-2",
    topic: "Passive voice",
    sentence: "The results ___ by the researchers next week.",
    options: ["will publish", "will be published", "are publishing"],
    correct: 1,
    explanation: "Future passive: 'will be + past participle'.",
    lessonId: "gram-passive-modals",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "passive voice",
  },
  {
    id: "g-comp-2",
    topic: "Comparatives",
    sentence: "The ___ you leave, the worse the traffic will be.",
    options: ["later", "latest", "more late"],
    correct: 0,
    explanation: "'The later…, the worse…' is a double comparative structure.",
    lessonId: "gram-comparisons-quantifiers",
    kind: "gap_fill",
    difficulty: 3,
    errorType: "comparatives",
  },
  {
    id: "g-modal-2",
    topic: "Modals",
    sentence: "You ___ submit the form by Friday, but it is not compulsory.",
    options: ["must", "may", "cannot"],
    correct: 1,
    explanation: "'May' expresses permission/possibility without obligation; 'must' would make it compulsory.",
    lessonId: "gram-passive-modals",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "modals",
  },
  {
    id: "g-parallel-2",
    topic: "Parallelism",
    sentence: "The course teaches reading, writing, and how to speak clearly.",
    options: ["and speaking clearly", "and to speak clearly", "no change"],
    correct: 0,
    explanation: "Parallel structure: 'reading, writing, and speaking clearly' keeps the gerund form consistent.",
    lessonId: "gram-parallelism",
    kind: "sentence_choice",
    difficulty: 2,
    errorType: "parallelism",
  },
  {
    id: "g-ref-1",
    topic: "Reference words",
    sentence: "Many cities have expanded rapidly. ___ has increased traffic congestion.",
    options: ["This", "They", "It is"],
    correct: 0,
    explanation: "'This' refers back to the whole previous idea, a common cohesive device.",
    lessonId: "gram-cohesion-reference",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "reference / cohesion",
  },
  {
    id: "g-count-1",
    topic: "Countability",
    sentence: "The report contains ___ evidence to support the claim.",
    options: ["many", "much", "a few"],
    correct: 1,
    explanation: "'Evidence' is uncountable, so 'much' is correct.",
    lessonId: "gram-articles-countability",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "countability",
  },
  {
    id: "g-prep-2",
    topic: "Prepositions",
    sentence: "The government is concerned ___ rising pollution levels.",
    options: ["about", "for", "on"],
    correct: 0,
    explanation: "'Concerned about' is the standard collocation.",
    lessonId: "gram-prepositions-collocations",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "prepositions / collocation",
  },
  {
    id: "g-frag-2",
    topic: "Fragments",
    sentence: "Which option IS a complete sentence?",
    options: ["Although the economy grew slowly.", "Because of the new policy.", "The policy reduced unemployment."],
    correct: 2,
    explanation: "Only the third has a subject ('the policy') and a main verb ('reduced'); the other two are dependent fragments.",
    lessonId: "gram-punctuation",
    kind: "sentence_choice",
    difficulty: 1,
    errorType: "sentence fragments",
  },
  {
    id: "g-runon-2",
    topic: "Run-on sentences",
    sentence: "Which fixes the run-on: 'Traffic increased, the city built new roads'?",
    options: ["Traffic increased, so the city built new roads.", "Traffic increased the city built new roads.", "no change"],
    correct: 0,
    explanation: "A coordinating conjunction ('so') or a semicolon is needed between two independent clauses.",
    lessonId: "gram-punctuation",
    kind: "sentence_choice",
    difficulty: 2,
    errorType: "run-on sentences",
  },
  {
    id: "g-punct-2",
    topic: "Punctuation",
    sentence: "Which correctly uses a comma after an introductory clause?",
    options: ["After the meeting ended the team celebrated.", "After the meeting ended, the team celebrated.", "After the meeting, ended the team celebrated."],
    correct: 1,
    explanation: "A comma follows the introductory adverbial clause 'After the meeting ended' before the main clause.",
    lessonId: "gram-punctuation",
    kind: "punctuation",
    difficulty: 1,
    errorType: "punctuation",
  },
  {
    id: "g-noun-2",
    topic: "Noun clauses",
    sentence: "___ the economy will recover is uncertain.",
    options: ["That", "Whether", "Because"],
    correct: 1,
    explanation: "'Whether' introduces a noun clause expressing an indirect yes/no question.",
    lessonId: "gram-noun-clauses",
    kind: "gap_fill",
    difficulty: 3,
    errorType: "noun clauses",
  },
  {
    id: "g-ger-2",
    topic: "Gerunds / infinitives",
    sentence: "Many students avoid ___ before the exam.",
    options: ["to study", "studying", "study"],
    correct: 1,
    explanation: "'Avoid' is followed by a gerund ('avoid studying').",
    lessonId: "gram-gerunds-infinitives",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "gerunds / infinitives",
  },
  {
    id: "g-adv-2",
    topic: "Adverbial clauses",
    sentence: "Which connector explicitly expresses contrast? '___ the price rose, demand remained stable.'",
    options: ["Although", "Because", "So"],
    correct: 0,
    explanation: "'Although' explicitly marks the contrast between the price increase and stable demand. 'Because' expresses cause, while 'so' cannot introduce this subordinate clause.",
    lessonId: "gram-adverbial-clauses",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "adverbial clauses / contrast",
  },
  {
    id: "g-conj-2",
    topic: "Conjunctions",
    sentence: "Which connector explicitly expresses concession in this sentence? 'The plan was popular ___ it was expensive.'",
    options: ["even though", "because", "therefore"],
    correct: 0,
    explanation: "'Even though' explicitly marks the surprising contrast between popularity and high cost.",
    lessonId: "gram-cohesion-reference",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "conjunctions",
  },
  {
    id: "g-cohesion-1",
    topic: "Cohesion",
    sentence: "Which connector explicitly expresses a result? 'Air pollution has risen sharply. ___, the city has introduced stricter vehicle-emission rules.'",
    options: ["Consequently", "Moreover", "For example"],
    correct: 0,
    explanation: "'Consequently' explicitly signals that the second sentence is the result of the first.",
    lessonId: "gram-cohesion-reference",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "cohesion / linking devices",
  },
  {
    id: "g-complex-1",
    topic: "Complex clauses",
    sentence: "Combine: 'The policy was expensive. It was still introduced.'",
    options: ["Although the policy was expensive, it was still introduced.", "The policy was expensive it was still introduced.", "The policy was expensive, but introduced it was."],
    correct: 0,
    explanation: "A subordinate clause with 'although' creates a correct complex sentence.",
    lessonId: "gram-complex-control",
    kind: "sentence_choice",
    difficulty: 2,
    errorType: "complex sentences",
  },
  {
    id: "g-boundary-1",
    topic: "Sentence boundaries",
    sentence: "Which option correctly joins the two clauses?",
    options: ["Many people work remotely. This saves time and money.", "Many people work remotely, this saves time and money.", "Many people work remotely this saves time and money."],
    correct: 0,
    explanation: "Two independent clauses need a full stop, semicolon or conjunction — not a comma alone.",
    lessonId: "gram-punctuation",
    kind: "sentence_choice",
    difficulty: 1,
    errorType: "sentence boundaries",
  },
  {
    id: "g-np-1",
    topic: "Noun phrases",
    sentence: "___ of urban housing is a major policy challenge.",
    options: ["The rapid rising cost", "The rapidly rising cost", "The rapid rise cost"],
    correct: 1,
    explanation: "Adverb 'rapidly' modifies the participle 'rising' inside the noun phrase.",
    lessonId: "gram-noun-phrases",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "noun phrases",
  },
  {
    id: "g-sv-4",
    topic: "Subject–verb agreement",
    sentence: "Every one of the students ___ required to attend.",
    options: ["are", "is", "were"],
    correct: 1,
    explanation: "'Every one' is singular, so the verb is 'is'.",
    lessonId: "gram-agreement",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "subject-verb agreement",
  },
  {
    id: "g-art-4",
    topic: "Articles",
    sentence: "She is ___ only person who knows the answer.",
    options: ["a", "the", "—"],
    correct: 1,
    explanation: "'The' is used with 'only' to mark uniqueness.",
    lessonId: "gram-articles-countability",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "articles",
  },
  {
    id: "g-tense-4",
    topic: "Tense consistency",
    sentence: "By 2030, the city ___ its population double.",
    options: ["will have seen", "has seen", "had seen"],
    correct: 0,
    explanation: "The future perfect ('will have seen') places the completed action before a future reference point. The present perfect and past perfect do not match the future time frame.",
    lessonId: "gram-tenses-conditionals",
    kind: "gap_fill",
    difficulty: 3,
    errorType: "tense",
  },
  {
    id: "g-cond-4",
    topic: "Conditionals",
    sentence: "If the government invests in railways, traffic congestion ___.",
    options: ["will decrease", "would decrease", "would have decreased"],
    correct: 0,
    explanation: "First conditional (real possibility): present in the if-clause, 'will' in the result.",
    lessonId: "gram-tenses-conditionals",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "conditionals",
  },
  {
    id: "g-rel-3",
    topic: "Relative clauses",
    sentence: "The city ___ I grew up has changed a lot.",
    options: ["where", "which", "that"],
    correct: 0,
    explanation: "'Where' is the relative adverb for place.",
    lessonId: "gram-relative-clauses",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "relative clauses",
  },
  {
    id: "g-pass-3",
    topic: "Passive voice",
    sentence: "Which is the correct passive?",
    options: ["A new hospital has built.", "A new hospital has been built.", "A new hospital is build."],
    correct: 1,
    explanation: "Present perfect passive: 'has been + past participle'.",
    lessonId: "gram-passive-modals",
    kind: "sentence_choice",
    difficulty: 2,
    errorType: "passive voice",
  },
  {
    id: "g-comp-3",
    topic: "Comparatives",
    sentence: "Public transport is ___ than driving in most cities.",
    options: ["more cheap", "cheaper", "more cheaper"],
    correct: 1,
    explanation: "'Cheap' is a one-syllable adjective, so the comparative is 'cheaper'.",
    lessonId: "gram-comparisons-quantifiers",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "comparatives",
  },
  {
    id: "g-modal-3",
    topic: "Modals",
    sentence: "Students ___ wear a uniform; it is optional.",
    options: ["must", "have to", "can"],
    correct: 2,
    explanation: "'Can' expresses permission without obligation, matching 'optional'.",
    lessonId: "gram-passive-modals",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "modals",
  },
  {
    id: "g-hedge-3",
    topic: "Hedging",
    sentence: "Which is the most appropriately hedged claim?",
    options: ["Technology definitely destroys all jobs.", "Technology tends to reduce certain types of routine work.", "Technology ruins everything."],
    correct: 1,
    explanation: "'Tends to' and 'certain types' make the claim appropriately cautious.",
    lessonId: "gram-academic-style",
    kind: "style_choice",
    difficulty: 2,
    errorType: "hedging",
  },
  {
    id: "g-count-2",
    topic: "Countability",
    sentence: "The research provides ___ useful information.",
    options: ["many", "a number of", "a great deal of"],
    correct: 2,
    explanation: "'Information' is uncountable; 'a great deal of' is used with uncountables.",
    lessonId: "gram-articles-countability",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "countability",
  },
  {
    id: "g-prep-3",
    topic: "Prepositions",
    sentence: "There has been a rise ___ the number of electric cars.",
    options: ["of", "in", "on"],
    correct: 1,
    explanation: "The standard collocation is 'a rise in'.",
    lessonId: "gram-prepositions-collocations",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "prepositions / collocation",
  },
  {
    id: "g-parallel-3",
    topic: "Parallelism",
    sentence: "Choose the sentence with parallel structure.",
    options: ["The essay discusses causes, effects, and to suggest solutions.", "The essay discusses causes, effects, and solutions.", "The essay discusses causes, effects and suggesting solutions."],
    correct: 1,
    explanation: "All three items are noun phrases, keeping the list parallel.",
    lessonId: "gram-parallelism",
    kind: "sentence_choice",
    difficulty: 1,
    errorType: "parallelism",
  },
  {
    id: "g-ref-2",
    topic: "Reference words",
    sentence: "Governments should invest in education. ___ brings long-term benefits.",
    options: ["This", "They", "It is"],
    correct: 0,
    explanation: "'This' refers back to the whole idea of investing in education.",
    lessonId: "gram-cohesion-reference",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "reference / cohesion",
  },
  {
    id: "g-formal-2",
    topic: "Formal academic style",
    sentence: "Which is most appropriate in an academic essay?",
    options: ["The government did a good job, basically.", "The policy achieved a measurable improvement in outcomes.", "It was a pretty good result, you know."],
    correct: 1,
    explanation: "Measured, precise vocabulary marks formal academic style.",
    lessonId: "gram-academic-style",
    kind: "style_choice",
    difficulty: 2,
    errorType: "formal style",
  },
  {
    id: "g-punct-3",
    topic: "Punctuation",
    sentence: "Which sentence uses commas correctly in a list?",
    options: ["The course covers reading writing and listening.", "The course covers reading, writing, and listening.", "The course covers, reading, writing, and listening."],
    correct: 1,
    explanation: "Commas separate the three items in the series.",
    lessonId: "gram-punctuation",
    kind: "punctuation",
    difficulty: 1,
    errorType: "punctuation",
  },
  {
    id: "g-sv-5",
    topic: "Subject–verb agreement",
    sentence: "The percentage of people who cycle to work ___ risen since 2010.",
    options: ["have", "has", "were"],
    correct: 1,
    explanation: "'The percentage' is singular, so the verb is 'has'.",
    lessonId: "gram-agreement",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "subject-verb agreement",
  },
  {
    id: "g-art-5",
    topic: "Articles",
    sentence: "___ number of cars on the road is increasing every year.",
    options: ["A", "The", "—"],
    correct: 1,
    explanation: "'The number of…' refers to a specific, defined quantity, so 'the' is used.",
    lessonId: "gram-articles-countability",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "articles",
  },
  {
    id: "g-tense-5",
    topic: "Tense consistency",
    sentence: "Since the policy was introduced, air quality ___ significantly.",
    options: ["improved", "has improved", "improves"],
    correct: 1,
    explanation: "Present perfect ('has improved') is used with 'since' for a change continuing to now.",
    lessonId: "gram-tenses-conditionals",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "tense",
  },
  {
    id: "g-cond-5",
    topic: "Conditionals",
    sentence: "If fewer people drove cars, congestion ___ less severe.",
    options: ["would be", "will be", "would have been"],
    correct: 0,
    explanation: "Second conditional (hypothetical present): past in the if-clause, 'would' in the result.",
    lessonId: "gram-tenses-conditionals",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "conditionals",
  },
  {
    id: "g-rel-4",
    topic: "Relative clauses",
    sentence: "Students ___ submit work late lose marks.",
    options: ["who", "which", "whose"],
    correct: 0,
    explanation: "'Who' refers to people (students).",
    lessonId: "gram-relative-clauses",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "relative clauses",
  },
  {
    id: "g-pass-4",
    topic: "Passive voice",
    sentence: "The new policy ___ by the government last month.",
    options: ["introduced", "was introduced", "has introduced"],
    correct: 1,
    explanation: "Past simple passive: 'was + past participle' for a completed past action.",
    lessonId: "gram-passive-modals",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "passive voice",
  },
  {
    id: "g-comp-4",
    topic: "Comparatives",
    sentence: "Air travel is far ___ than rail travel in terms of emissions.",
    options: ["more damaging", "damaginger", "most damaging"],
    correct: 0,
    explanation: "'Damaging' is a long adjective, so the comparative is 'more damaging'.",
    lessonId: "gram-comparisons-quantifiers",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "comparatives",
  },
  {
    id: "g-modal-4",
    topic: "Modals",
    sentence: "Governments ___ invest more in public transport; this is a recommendation, not a legal requirement.",
    options: ["should", "must", "cannot"],
    correct: 0,
    explanation: "'Should' expresses recommendation/advice. 'Must' would express a stronger requirement, which the context explicitly rules out, and 'cannot' contradicts the recommendation.",
    lessonId: "gram-passive-modals",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "modals",
  },
  {
    id: "g-hedge-4",
    topic: "Hedging",
    sentence: "Which statement is most cautious about research findings?",
    options: ["The study proves all students benefit.", "The study suggests that many students may benefit.", "The study definitely solves every problem."],
    correct: 1,
    explanation: "'Suggests' and 'may' appropriately limit the strength of the claim.",
    lessonId: "gram-academic-style",
    kind: "style_choice",
    difficulty: 2,
    errorType: "hedging",
  },
  {
    id: "g-count-3",
    topic: "Countability",
    sentence: "There are ___ opportunities for skilled workers in the city.",
    options: ["much", "a great deal of", "many"],
    correct: 2,
    explanation: "'Opportunities' is countable and plural, so 'many' is correct.",
    lessonId: "gram-articles-countability",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "countability",
  },
  {
    id: "g-prep-4",
    topic: "Prepositions",
    sentence: "The graph shows a decrease ___ crime rates over the decade.",
    options: ["of", "in", "on"],
    correct: 1,
    explanation: "The standard collocation is 'a decrease in'.",
    lessonId: "gram-prepositions-collocations",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "prepositions / collocation",
  },
  {
    id: "g-parallel-4",
    topic: "Parallelism",
    sentence: "Choose the option that keeps the verb forms consistent.",
    options: ["The programme improved literacy, reduced dropout rates and encouraging attendance.", "The programme improved literacy, reduced dropout rates and encouraged attendance.", "The programme improved literacy, reducing dropout rates and encouraged attendance."],
    correct: 1,
    explanation: "All three verbs are in the past tense, keeping the list parallel.",
    lessonId: "gram-parallelism",
    kind: "sentence_choice",
    difficulty: 2,
    errorType: "parallelism",
  },
  {
    id: "g-ref-3",
    topic: "Reference words",
    sentence: "The policy has many critics. ___ remains popular with voters.",
    options: ["It", "They", "These"],
    correct: 0,
    explanation: "'It' refers back to the singular noun 'the policy'; the plural pronouns do not agree.",
    lessonId: "gram-cohesion-reference",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "reference / cohesion",
  },
  {
    id: "g-formal-3",
    topic: "Formal academic style",
    sentence: "Which is most appropriate in an academic essay?",
    options: ["Lots of people think homework is useless.", "A significant number of researchers question the value of homework.", "Homework is a total waste of time, basically."],
    correct: 1,
    explanation: "The middle option uses measured, formal academic vocabulary.",
    lessonId: "gram-academic-style",
    kind: "style_choice",
    difficulty: 2,
    errorType: "formal style",
  },
  {
    id: "g-boundary-2",
    topic: "Sentence boundaries",
    sentence: "Which correctly joins the two ideas?",
    options: ["The population grew rapidly, housing became scarce.", "The population grew rapidly; housing became scarce.", "The population grew rapidly housing became scarce."],
    correct: 1,
    explanation: "A semicolon correctly joins two closely related independent clauses.",
    lessonId: "gram-punctuation",
    kind: "sentence_choice",
    difficulty: 1,
    errorType: "sentence boundaries",
  },
  {
    id: "g-np-2",
    topic: "Noun phrases",
    sentence: "___ of public transport is a priority for many cities.",
    options: ["The expansion", "The expand", "The expanded"],
    correct: 0,
    explanation: "'Expansion' is the noun form needed as the head of the noun phrase.",
    lessonId: "gram-noun-phrases",
    kind: "gap_fill",
    difficulty: 1,
    errorType: "noun phrases",
  },
  {
    id: "g-cohesion-2",
    topic: "Cohesion",
    sentence: "Choose the connector that expresses a result: 'Unemployment rose sharply. ___, consumer spending fell.'",
    options: ["As a result", "For instance", "Similarly"],
    correct: 0,
    explanation: "'As a result' explicitly signals the causal consequence of rising unemployment.",
    lessonId: "gram-cohesion-reference",
    kind: "gap_fill",
    difficulty: 2,
    errorType: "cohesion / linking devices",
  },
  {
    id: "g-complex-2",
    topic: "Complex clauses",
    sentence: "Combine: 'The city banned cars. Air quality improved.'",
    options: ["After the city banned cars, air quality improved.", "The city banned cars air quality improved.", "The city banned cars, improved air quality."],
    correct: 0,
    explanation: "A subordinating conjunction ('after') creates a correct complex sentence.",
    lessonId: "gram-complex-control",
    kind: "sentence_choice",
    difficulty: 2,
    errorType: "complex sentences",
  },
  {
    id: "g-punct-4",
    topic: "Punctuation",
    sentence: "Choose the correct apostrophe use.",
    options: ["Its a well-known fact that rents are rising.", "It's a well-known fact that rents are rising.", "Its' a well-known fact that rents are rising."],
    correct: 1,
    explanation: "'It's' is a contraction of 'it is'; 'its' (no apostrophe) is the possessive, and 'its'' does not exist.",
    lessonId: "gram-punctuation",
    kind: "punctuation",
    difficulty: 1,
    errorType: "punctuation / apostrophes",
  },
];

// ---- Round 5 additions ----
function E(
  id: string,
  lessonId: string,
  topic: string,
  kind: GrammarExerciseKind,
  difficulty: 1 | 2 | 3,
  sentence: string,
  options: string[],
  correct: number,
  explanation: string,
  errorType: string,
): GrammarExercise {
  return { id, topic, sentence, options, correct, explanation, errorType, lessonId, kind, difficulty };
}

grammarExercises.push(
  // --- gram-sentences (+8) ---
  E("g-sent-1", "gram-sentences", "Sentence structure", "sentence_choice", 1,
    "Which is a simple sentence?", ["Although it was late, she kept working.", "She kept working until midnight.", "She kept working, and he made tea."], 1,
    "A simple sentence has exactly one independent clause and no dependent clause or second clause joined by a conjunction.", "sentence types"),
  E("g-sent-2", "gram-sentences", "Sentence structure", "sentence_choice", 1,
    "Which is a compound sentence?", ["Because demand fell, prices dropped.", "Demand fell, so prices dropped.", "Demand falling sharply last year."], 1,
    "Two independent clauses joined by 'so' form a compound sentence.", "sentence types"),
  E("g-sent-3", "gram-sentences", "Sentence structure", "sentence_choice", 2,
    "Which is a complex sentence?", ["The train was late, and we missed the meeting.", "Although the train was late, we caught the meeting.", "The train being late, we missed it."], 1,
    "A dependent clause ('Although the train was late') plus an independent clause forms a complex sentence.", "sentence types"),
  E("g-sent-4", "gram-sentences", "Sentence structure", "sentence_choice", 2,
    "Which is a compound-complex sentence?", ["Although it rained, we walked, and we enjoyed it.", "It rained, but we walked.", "We walked in the rain."], 0,
    "Two independent clauses joined by 'and' plus a dependent clause ('Although it rained') make a compound-complex sentence.", "sentence types"),
  E("g-sent-5", "gram-sentences", "Sentence structure", "sentence_choice", 1,
    "Choose the sentence that varies structure best in an essay.", ["Cars are convenient. Cars pollute. Cars are expensive.", "Cars are convenient, yet they pollute and remain expensive for many households.", "Cars convenient and pollute and expensive."], 1,
    "The second option combines related ideas into one controlled complex sentence instead of chaining short sentences.", "sentence variety"),
  E("g-sent-6", "gram-sentences", "Sentence structure", "error_identification", 2,
    "Identify the problem: 'Cycling is healthy it also saves money.'", ["missing verb", "two clauses joined without a connector", "wrong article"], 1,
    "Two independent clauses are joined with no connector — this is a run-on sentence.", "run-on sentences"),
  E("g-sent-7", "gram-sentences", "Sentence structure", "gap_fill", 2,
    "Which connector explicitly expresses contrast? 'Public transport reduces congestion, ___ many commuters still prefer driving.'", ["but", "so", "because"], 0,
    "'But' explicitly marks the contrast between the benefit of public transport and commuters' continued preference for driving.", "conjunctions"),
  E("g-sent-8", "gram-sentences", "Sentence structure", "sentence_choice", 3,
    "Which sentence shows controlled variety?", ["The survey shows a rise. The survey shows a fall in another group. The survey shows an overall change.", "While one group rose, another fell, yet the overall trend remained positive.", "Rise and fall and overall change in the survey."], 1,
    "One controlled complex sentence expresses the same ideas more efficiently and naturally.", "sentence variety"),

  // --- gram-clauses (+8) ---
  E("g-clause-1", "gram-clauses", "Clauses and clause boundaries", "sentence_choice", 1,
    "Which contains one independent and one dependent clause?", ["She studies late and wakes early.", "Because she studies late, she wakes early.", "She studies late, wakes early."], 1,
    "'Because she studies late' is a dependent clause; 'she wakes early' is independent.", "clause types"),
  E("g-clause-2", "gram-clauses", "Clauses and clause boundaries", "sentence_choice", 2,
    "Which correctly punctuates the introductory clause?", ["When the course finished everyone celebrated.", "When the course finished, everyone celebrated.", "When the course finished; everyone celebrated."], 1,
    "A dependent clause at the start of a sentence is followed by a comma before the main clause.", "punctuation"),
  E("g-clause-3", "gram-clauses", "Clauses and clause boundaries", "sentence_choice", 1,
    "Which is a dependent clause?", ["The results were surprising.", "If the results are surprising", "The results surprised everyone."], 1,
    "A clause beginning with 'if' is dependent and cannot stand alone.", "clause types"),
  E("g-clause-4", "gram-clauses", "Clauses and clause boundaries", "error_identification", 2,
    "Identify the error: 'The policy was popular, it was expensive.'", ["comma splice", "fragment", "wrong tense"], 0,
    "Two independent clauses joined with only a comma is a comma splice; use a semicolon, a conjunction, or a full stop.", "comma splice"),
  E("g-clause-5", "gram-clauses", "Clauses and clause boundaries", "gap_fill", 2,
    "Which connector explicitly expresses concession? '___ the survey was short, the results were still reliable.'", ["Although", "Because", "Since"], 0,
    "'Although' marks the concessive contrast between the survey's short length and the reliability of the results. 'Because' and 'since' express cause instead.", "concession"),
  E("g-clause-6", "gram-clauses", "Clauses and clause boundaries", "sentence_choice", 3,
    "Choose the correctly joined pair.", ["The shop closed early; because of the storm.", "The shop closed early because of the storm.", "Because the shop closed early, and the storm."], 1,
    "A main clause plus 'because of + noun phrase' forms a grammatical sentence.", "cause clauses"),
  E("g-clause-7", "gram-clauses", "Clauses and clause boundaries", "gap_fill", 2,
    "She will start the course ___ she has saved enough money.", ["once", "during", "because of"], 0,
    "'Once' means 'as soon as'; 'during' and 'because of' cannot join these clauses ('because of' needs a noun phrase).", "time clauses"),
  E("g-clause-8", "gram-clauses", "Clauses and clause boundaries", "sentence_choice", 2,
    "Which sentence contains an adverbial clause?", ["The museum, which opened in May, is popular.", "We visited the museum after it opened in May.", "The new museum is popular."], 1,
    "'after it opened in May' is an adverbial clause of time.", "adverbial clauses"),

  // --- gram-agreement (+3) ---
  E("g-agree-6", "gram-agreement", "Subject–verb agreement", "gap_fill", 2,
    "The amount of plastic waste in oceans ___ increasing every year.", ["are", "is", "were"], 1,
    "'The amount' is singular, so the verb must be 'is'.", "subject-verb agreement"),
  E("g-agree-7", "gram-agreement", "Subject–verb agreement", "gap_fill", 2,
    "Each of the candidates ___ asked to give a short presentation.", ["were", "was", "have been"], 1,
    "'Each' is singular; ignore the 'of' phrase when choosing the verb.", "subject-verb agreement"),
  E("g-agree-8", "gram-agreement", "Subject–verb agreement", "gap_fill", 3,
    "The results from the survey ___ inconclusive.", ["are", "is", "be"], 0,
    "'Results' is plural, so the plural verb 'are' is required.", "subject-verb agreement"),

  // --- gram-relative-clauses (+4) ---
  E("g-rel-5", "gram-relative-clauses", "Relative clauses", "gap_fill", 2,
    "The professor ___ research was published last month is giving a talk.", ["who", "whose", "which"], 1,
    "'Whose' shows possession: the professor's research.", "relative clauses"),
  E("g-rel-6", "gram-relative-clauses", "Relative clauses", "gap_fill", 1,
    "The café ___ we met has closed down.", ["where", "which", "who"], 0,
    "'Where' refers to a place (the café).", "relative clauses"),
  E("g-rel-7", "gram-relative-clauses", "Relative clauses", "sentence_choice", 2,
    "Which correctly punctuates a non-defining relative clause?", ["My sister, that lives abroad, is visiting.", "My sister, who lives abroad, is visiting.", "My sister who lives abroad, is visiting."], 1,
    "Non-defining relative clauses use 'who' (not 'that') and need commas on both sides.", "relative clauses"),
  E("g-rel-8", "gram-relative-clauses", "Relative clauses", "sentence_choice", 3,
    "Which sentence can omit the relative pronoun?", ["The policy that was introduced last year is working.", "The policy that the council introduced last year is working.", "The policy, which was introduced last year, is working."], 1,
    "The pronoun can be omitted only when it is the object of a defining clause ('the policy that the council introduced').", "relative clauses"),

  // --- gram-noun-clauses (+6) ---
  E("g-nounclause-3", "gram-noun-clauses", "Noun clauses", "gap_fill", 2,
    "The figures support the claim ___ demand has fallen for the third consecutive year.", ["that", "whether", "if"], 0,
    "'The claim that…' is the standard pattern for stating the content of a claim; 'whether/if' cannot follow the noun 'claim'.", "noun clauses"),
  E("g-nounclause-4", "gram-noun-clauses", "Noun clauses", "gap_fill", 2,
    "___ the scheme will be extended is still uncertain.", ["Whether", "That", "Because"], 0,
    "'Whether' introduces a yes/no idea as the subject of the sentence.", "noun clauses"),
  E("g-nounclause-5", "gram-noun-clauses", "Noun clauses", "error_identification", 2,
    "Identify the error: 'I don't know where is the station.'", ["word order", "missing article", "wrong verb"], 0,
    "Noun clauses keep statement word order: 'where the station is'.", "noun clauses"),
  E("g-nounclause-6", "gram-noun-clauses", "Noun clauses", "sentence_choice", 2,
    "Which uses exactly one connector with 'the question is'?", ["The question is that whether prices will fall.", "The question is whether prices will fall.", "The question is if that prices will fall."], 1,
    "Use a single connector: 'whether', not 'that whether'.", "noun clauses"),
  E("g-nounclause-7", "gram-noun-clauses", "Noun clauses", "gap_fill", 3,
    "The committee is still considering both outcomes and has not yet decided ___ the proposal will be accepted or rejected.", ["whether", "that", "because"], 0,
    "'Whether' introduces an unresolved choice between acceptance and rejection. 'That' would present acceptance as the content of a decision rather than an open alternative.", "noun clauses"),
  E("g-nounclause-8", "gram-noun-clauses", "Noun clauses", "sentence_choice", 2,
    "Which uses a noun clause as subject?", ["What the study reveals is significant.", "The study reveals a significant trend.", "The study is significant."], 0,
    "'What the study reveals' is a noun clause acting as the subject.", "noun clauses"),

  // --- gram-adverbial-clauses (+6) ---
  E("g-adv-3", "gram-adverbial-clauses", "Adverbial clauses", "error_identification", 2,
    "Identify the error: 'Although it was expensive, but they bought it.'", ["double connector", "wrong tense", "missing comma"], 0,
    "'Although' and 'but' cannot both join the same clauses — use one.", "adverbial clauses"),
  E("g-adv-4", "gram-adverbial-clauses", "Adverbial clauses", "gap_fill", 2,
    "Which connector explicitly expresses contrast? '___ it was raining heavily, the match went ahead.'", ["Although", "Because", "Since"], 0,
    "'Although' explicitly marks the contrast between the heavy rain and the match going ahead. 'Because' and 'since' express cause, which the context does not support.", "adverbial clauses"),
  E("g-adv-5", "gram-adverbial-clauses", "Adverbial clauses", "sentence_choice", 1,
    "Which correctly punctuates the conditional clause?", ["If the price rises demand will fall.", "If the price rises, demand will fall.", "If the price rises; demand will fall."], 1,
    "A conditional clause at the start of the sentence takes a comma before the main clause.", "adverbial clauses"),
  E("g-adv-6", "gram-adverbial-clauses", "Adverbial clauses", "gap_fill", 2,
    "She has worked from home ___ the start of the pandemic.", ["since", "for", "while"], 0,
    "'Since' marks the starting point of the continuing action; 'for' needs a duration and 'while' a clause.", "adverbial clauses"),
  E("g-adv-7", "gram-adverbial-clauses", "Adverbial clauses", "error_identification", 2,
    "Identify the error: 'Because of the train was late, we missed the start.'", ["because of + clause", "tense", "word order"], 0,
    "'Because of' takes a noun phrase; use 'because the train was late' or 'because of the late train'.", "adverbial clauses"),
  E("g-adv-8", "gram-adverbial-clauses", "Adverbial clauses", "gap_fill", 3,
    "Which connector explicitly expresses concession? 'Demand held up ___ costs rose sharply.'", ["even though", "because", "so"], 0,
    "'Even though' introduces concession: demand remained strong despite rising costs. 'Because' expresses cause, while 'so' does not fit the requested concessive relation.", "adverbial clauses"),

  // --- gram-participle-clauses (+8) ---
  E("g-part-1", "gram-participle-clauses", "Participle clauses", "gap_fill", 2,
    "___ in 1902, the bridge is now a museum.", ["Built", "Building", "Being built"], 0,
    "'Built' is passive: the bridge was built, so the -ed participle is used.", "participle clauses"),
  E("g-part-2", "gram-participle-clauses", "Participle clauses", "gap_fill", 2,
    "Households ___ solar panels have lower electricity bills.", ["using", "used", "to use"], 0,
    "Active meaning ('households that use') takes the -ing participle.", "participle clauses"),
  E("g-part-3", "gram-participle-clauses", "Participle clauses", "sentence_choice", 3,
    "Which sentence correctly uses an opening participle clause?", ["Walking to school, the bus passed us.", "While we were walking to school, the bus passed us.", "Walking to school, we saw the bus pass us."], 2,
    "Only C opens with a participle clause whose implied subject 'we' matches the main clause subject; A is dangling and B has no participle clause.", "participle clauses"),
  E("g-part-4", "gram-participle-clauses", "Participle clauses", "sentence_choice", 2,
    "Which correctly uses the passive participle expression 'faced with'?", ["Faced with rising rents, many people delay buying a home.", "Facing with rising rents, many people delay buying.", "Faced by rising rents, many people are delaying to buy."], 0,
    "'Faced with' is the standard passive participle expression for a situation.", "participle clauses"),
  E("g-part-5", "gram-participle-clauses", "Participle clauses", "gap_fill", 2,
    "The graph shows spending ___ sharply in 2019.", ["rising", "risen", "to rise"], 0,
    "'Shows + noun + -ing' uses the participle to describe the movement; 'to rise' does not fit this pattern.", "participle clauses"),
  E("g-part-6", "gram-participle-clauses", "Participle clauses", "sentence_choice", 3,
    "Which correctly uses the passive participle 'written'?", ["The report, written by two researchers, was well received.", "The report, writing by two researchers, was well received.", "The report, wrote by two researchers, was well received."], 0,
    "The passive participle 'written' describes the report.", "participle clauses"),
  E("g-part-7", "gram-participle-clauses", "Participle clauses", "gap_fill", 2,
    "___ all the options, the committee chose the cheapest.", ["Having considered", "Considered", "To consider"], 0,
    "'Having considered' shows the action was completed before choosing; the other forms do not express that sequence.", "participle clauses"),
  E("g-part-8", "gram-participle-clauses", "Participle clauses", "sentence_choice", 2,
    "Which correctly uses 'given' to introduce a condition?", ["Given more time, the results would improve.", "Giving more time, the results would improve.", "To give more time, the results would improve."], 0,
    "'Given more time' is a passive participle meaning 'if more time were given'.", "participle clauses"),

  // --- gram-gerunds-infinitives (+6) ---
  E("g-ger-3", "gram-gerunds-infinitives", "Gerunds / infinitives", "gap_fill", 2,
    "She avoided ___ about the problem in the meeting.", ["to talk", "talking", "talk"], 1,
    "'Avoid' is followed by a gerund.", "gerunds / infinitives"),
  E("g-ger-4", "gram-gerunds-infinitives", "Gerunds / infinitives", "gap_fill", 2,
    "They decided ___ the project until next year.", ["delaying", "to delay", "delay"], 1,
    "'Decide' is followed by the to-infinitive.", "gerunds / infinitives"),
  E("g-ger-5", "gram-gerunds-infinitives", "Gerunds / infinitives", "sentence_choice", 2,
    "Which correctly uses 'remember + -ing' for a past experience?", ["I remember to visit the museum as a child.", "I remember visiting the museum as a child.", "I remember visit the museum as a child."], 1,
    "'Remember doing' refers to a past experience; 'remember to do' would mean a future task.", "gerunds / infinitives"),
  E("g-ger-6", "gram-gerunds-infinitives", "Gerunds / infinitives", "gap_fill", 1,
    "He is interested in ___ abroad.", ["study", "studying", "to study"], 1,
    "After a preposition ('in') use the -ing form.", "gerunds / infinitives"),
  E("g-ger-7", "gram-gerunds-infinitives", "Gerunds / infinitives", "gap_fill", 2,
    "The report suggests ___ public transport more affordable.", ["to make", "making", "make"], 1,
    "'Suggest' takes a gerund (suggest making).", "gerunds / infinitives"),
  E("g-ger-8", "gram-gerunds-infinitives", "Gerunds / infinitives", "sentence_choice", 3,
    "Which correctly uses 'stop to do' to show purpose?", ["She stopped to answer the phone.", "She stopped answer the phone.", "She stopped to answering the phone."], 0,
    "'Stop to do' means stopping one action in order to do another.", "gerunds / infinitives"),

  // --- gram-comparisons-quantifiers (+4) ---
  E("g-comp-5", "gram-comparisons-quantifiers", "Comparatives", "gap_fill", 2,
    "Sales in 2020 were twice ___ high ___ in 2010.", ["as / as", "so / than", "more / than"], 0,
    "The structure is 'twice as + adjective + as'.", "comparatives"),
  E("g-comp-6", "gram-comparisons-quantifiers", "Comparatives", "gap_fill", 2,
    "The north region performed ___ better than the south.", ["far", "more", "much more"], 0,
    "'Far better' intensifies the comparative correctly (avoid 'more better').", "comparatives"),
  E("g-comp-7", "gram-comparisons-quantifiers", "Comparatives", "gap_fill", 3,
    "Which connector explicitly contrasts the two trends? 'Car use fell, ___ cycling increased significantly.'", ["whereas", "because", "therefore"], 0,
    "'Whereas' contrasts the fall in car use with the rise in cycling. 'Because' expresses cause and 'therefore' expresses result.", "comparatives"),
  E("g-comp-8", "gram-comparisons-quantifiers", "Comparatives", "gap_fill", 2,
    "Monthly rents in London and Bristol were £800 and £650 ______.", ["each", "respectively", "individually"], 1,
    "'Respectively' maps the figures to the two named cities in order: London → £800, Bristol → £650.", "comparatives"),

  // --- gram-prepositions-collocations (+4) ---
  E("g-prep-5", "gram-prepositions-collocations", "Prepositions", "gap_fill", 2,
    "The chart shows a rise ___ the number of cyclists.", ["of", "in", "on"], 1,
    "The standard collocation is 'a rise in'.", "prepositions / collocation"),
  E("g-prep-6", "gram-prepositions-collocations", "Prepositions", "gap_fill", 1,
    "We discussed ___ the proposal for an hour.", ["about", "on", "—"], 2,
    "'Discuss' takes a direct object with no preposition.", "prepositions / collocation"),
  E("g-prep-7", "gram-prepositions-collocations", "Prepositions", "gap_fill", 2,
    "There are several possible solutions ___ the housing shortage.", ["of", "to", "with"], 1,
    "The standard collocation is 'solutions to' (a problem).", "prepositions / collocation"),
  E("g-prep-8", "gram-prepositions-collocations", "Prepositions", "gap_fill", 3,
    "Prices remained stable ___ the period.", ["over", "since", "until"], 0,
    "'Over the period' describes a span of time.", "prepositions / collocation"),

  // --- gram-cohesion-reference (+1) ---
  E("g-coh-3", "gram-cohesion-reference", "Cohesion", "gap_fill", 2,
    "Which connector explicitly expresses addition? 'Rents have risen sharply. ___, transport costs have also increased.'", ["In addition", "As a result", "In contrast"], 0,
    "'In addition' adds a second similar trend. 'As a result' expresses a cause-effect relation and 'In contrast' a difference, so neither matches the requested function of addition.", "cohesion / linking devices"),

  // --- gram-parallelism (+4) ---
  E("g-par-5", "gram-parallelism", "Parallelism", "sentence_choice", 2,
    "Choose the parallel version.", ["The course teaches reading, writing and how to speak clearly.", "The course teaches reading, writing and speaking clearly.", "The course teaches reading, writing and clearly speaking."], 1,
    "All three items are gerunds, keeping the list parallel.", "parallelism"),
  E("g-par-6", "gram-parallelism", "Parallelism", "gap_fill", 2,
    "The policy aims to reduce traffic, improve air quality and ___ money.", ["saving", "save", "to save"], 1,
    "After 'aims to', coordinated infinitives may share the first 'to': to reduce, improve and save.", "parallelism"),
  E("g-par-7", "gram-parallelism", "Parallelism", "error_identification", 2,
    "Identify the error: 'The scheme reduced costs, improved safety, and it saved time.'", ["non-parallel list", "tense", "article"], 0,
    "The third item 'it saved time' breaks the parallel verb pattern.", "parallelism"),
  E("g-par-8", "gram-parallelism", "Parallelism", "sentence_choice", 3,
    "Choose the parallel version.", ["Not only did sales rise, but profits also increased.", "Not only sales rose, but also profits increased.", "Sales not only rose, but profits increased also."], 0,
    "Inversion after 'Not only' keeps the two clauses balanced and parallel.", "parallelism"),

  // --- gram-noun-phrases (+6) ---
  E("g-np-3", "gram-noun-phrases", "Noun phrases", "gap_fill", 2,
    "___ of the new metro line took two years.", ["The construction", "The construct", "The constructed"], 0,
    "The noun 'construction' is needed as the head of the noun phrase.", "noun phrases"),
  E("g-np-4", "gram-noun-phrases", "Noun phrases", "gap_fill", 2,
    "The ___ cost of housing is a major concern.", ["rapidly rising", "rapid rise", "rapid risen"], 0,
    "Adverb 'rapidly' modifies the participle 'rising' inside the noun phrase.", "noun phrases"),
  E("g-np-5", "gram-noun-phrases", "Noun phrases", "sentence_choice", 2,
    "Which uses nominalisation?", ["The government decided to invest.", "The government's decision to invest was welcomed.", "The government will invest."], 1,
    "'Decision' nominalises the verb 'decide'.", "noun phrases"),
  E("g-np-6", "gram-noun-phrases", "Noun phrases", "gap_fill", 3,
    "A rapid increase ___ prices was recorded.", ["of", "in", "on"], 1,
    "The noun 'increase' takes 'in' before what changed.", "noun phrases"),
  E("g-np-7", "gram-noun-phrases", "Noun phrases", "sentence_choice", 2,
    "Choose the clearest academic noun phrase.", ["the people who live in the city and are young", "young urban residents", "people young living in city"], 1,
    "A compact noun phrase is clearer and more academic than a long relative clause.", "noun phrases"),
  E("g-np-8", "gram-noun-phrases", "Noun phrases", "gap_fill", 2,
    "The ___ of the new policy is still being discussed.", ["introduction", "introduce", "introducing"], 0,
    "The noun form 'introduction' is needed after 'the'.", "noun phrases"),

  // --- gram-complex-control (+6) ---
  E("g-cx-1", "gram-complex-control", "Complex clauses", "sentence_choice", 3,
    "Choose the better essay sentence.", ["There are many people use cars because it is convenient.", "Many people use cars because they are convenient.", "Many people use cars convenient."], 1,
    "The second sentence is accurate; the first wrongly doubles the subject ('there are many people use').", "complex sentences"),
  E("g-cx-2", "gram-complex-control", "Complex clauses", "sentence_choice", 2,
    "Which sentence combines the ideas most clearly?", ["The policy was expensive. It was introduced. It reduced fares.", "Although expensive, the policy reduced fares.", "The policy expensive reduced fares."], 1,
    "'Although expensive' compresses the concession without a run-on.", "complex sentences"),
  E("g-cx-3", "gram-complex-control", "Complex clauses", "error_identification", 3,
    "Identify the problem: 'The more people cycle, the roads become safer.'", ["incomplete double comparative", "tense", "article"], 0,
    "The second half of the double comparative is incomplete: it needs 'the safer the roads become'.", "complex sentences"),
  E("g-cx-4", "gram-complex-control", "Complex clauses", "gap_fill", 3,
    "The more you practise, ___ your accuracy becomes.", ["the better", "better", "the best"], 0,
    "Double comparative: 'the more…, the better…'.", "complex sentences"),
  E("g-cx-5", "gram-complex-control", "Complex clauses", "sentence_choice", 2,
    "Which correctly uses 'because' with a clause?", ["Because of it rained, the event was cancelled.", "Because it rained, the event was cancelled.", "Because raining, the event was cancelled."], 1,
    "'Because + clause' is grammatical; 'because of' needs a noun phrase.", "complex sentences"),
  E("g-cx-6", "gram-complex-control", "Complex clauses", "sentence_choice", 3,
    "Which sentence correctly uses a non-defining relative clause?", ["The scheme which the council launched has reduced traffic.", "The scheme, which the council launched has reduced traffic.", "The scheme, which the council launched, has reduced traffic."], 2,
    "A non-defining relative clause requires commas on both sides. Option A is a valid defining relative clause, but it does not satisfy the question.", "complex sentences"),

  // --- gram-academic-style (+2) ---
  E("g-style-4", "gram-academic-style", "Formal academic style", "style_choice", 2,
    "Choose the most academic wording.", ["Kids watch too much TV.", "Children's excessive television viewing has been linked to negative outcomes.", "Watching telly a lot is bad for kids."], 1,
    "The second option uses formal vocabulary and nominalisation.", "formal style"),
  E("g-style-5", "gram-academic-style", "Hedging", "style_choice", 3,
    "Which claim is appropriately hedged?", ["Online learning always harms social skills.", "Online learning may limit face-to-face interaction for some students.", "Online learning destroys all social development."], 1,
    "'May' and 'for some students' limit the claim to what the evidence supports.", "hedging"),

  // --- gram-task1-grammar (+12) ---
  E("g-t1-1", "gram-task1-grammar", "Academic Task 1 grammar", "gap_fill", 2,
    "Sales ___ steadily between 2000 and 2010.", ["rose", "have risen", "rise"], 0,
    "A completed past period takes the past simple.", "tense"),
  E("g-t1-2", "gram-task1-grammar", "Academic Task 1 grammar", "gap_fill", 2,
    "Sales ___ steadily since 2000.", ["rose", "have risen", "rise"], 1,
    "'Since' with a continuing period takes the present perfect.", "tense"),
  E("g-t1-3", "gram-task1-grammar", "Academic Task 1 grammar", "gap_fill", 2,
    "Demand is predicted ___ sharply next year.", ["to fall", "falling", "falls"], 0,
    "'Is predicted to + verb' expresses a projection.", "tense"),
  E("g-t1-4", "gram-task1-grammar", "Academic Task 1 grammar", "gap_fill", 1,
    "Car use fell, ___ cycling rose.", ["whereas", "while it", "despite"], 0,
    "'Whereas' contrasts the two trends; 'while it' is ungrammatical and 'despite' needs a noun phrase.", "comparison"),
  E("g-t1-5", "gram-task1-grammar", "Academic Task 1 grammar", "gap_fill", 2,
    "Sales of Product A and Product B were 40 and 25 units ______.", ["each", "respectively", "both"], 1,
    "'Respectively' maps each value to the previously listed entity in the same order: Product A → 40, Product B → 25.", "comparison"),
  E("g-t1-6", "gram-task1-grammar", "Academic Task 1 grammar", "gap_fill", 2,
    "There was an increase ___ 5% in output.", ["of", "in", "by"], 0,
    "'An increase of + figure'; the verb form uses 'by' (rose by 5%).", "preposition"),
  E("g-t1-7", "gram-task1-grammar", "Academic Task 1 grammar", "gap_fill", 2,
    "The bottles ___ collected, sorted and crushed.", ["are", "have", "been"], 0,
    "Process descriptions use the present simple passive: 'are collected, sorted and crushed'.", "passive"),
  E("g-t1-8", "gram-task1-grammar", "Academic Task 1 grammar", "gap_fill", 2,
    "The factory was converted ___ apartments.", ["into", "as", "over"], 0,
    "'Converted into' describes the new use; 'as' and 'over' are not used in this pattern.", "map language"),
  E("g-t1-9", "gram-task1-grammar", "Academic Task 1 grammar", "sentence_choice", 2,
    "Choose the correct Task 1 sentence.", ["The percentage of car users decreased from 65% to 45%.", "The percentage of car users decreased from 65 to 45%.", "The percentage of car users decreased from 65% until 45%."], 0,
    "Both figures need the per cent sign, and a change of level takes 'from…to…', not 'until'.", "percentage"),
  E("g-t1-10", "gram-task1-grammar", "Academic Task 1 grammar", "gap_fill", 3,
    "Overall, the figures show a clear upward ______.", ["tendency", "tend", "tending"], 0,
    "The noun 'tendency' is required after 'a clear upward'.", "noun form"),
  E("g-t1-11", "gram-task1-grammar", "Academic Task 1 grammar", "sentence_choice", 2,
    "Which overview is grammatically correct?", ["Overall, all categories increased, with transport recording the largest rise.", "Overall all categories increased, with transport recorded the largest rise.", "Overall, all categories increased, with transport record the largest rise."], 0,
    "'With + noun + -ing' (with transport recording the largest rise) adds a supplementary detail; 'recorded' and 'record' break that pattern.", "complex sentences"),
  E("g-t1-12", "gram-task1-grammar", "Academic Task 1 grammar", "gap_fill", 2,
    "Electricity generation by coal fell ___ 320 to 210 GWh.", ["from", "between", "of"], 0,
    "'From X to Y' expresses the range of change.", "preposition"),

  // --- gram-task2-grammar (+12) ---
  E("g-t2-1", "gram-task2-grammar", "Task 2 argument grammar", "gap_fill", 2,
    "Which connector explicitly introduces concession? '___ online learning is flexible, it can also leave some students feeling isolated.'", ["Although", "Therefore", "For example"], 0,
    "'Although' introduces a concessive contrast: flexibility is a benefit, while isolation is a disadvantage.", "concession"),
  E("g-t2-2", "gram-task2-grammar", "Task 2 argument grammar", "gap_fill", 2,
    "Higher fuel prices may ___ to a fall in car use.", ["lead", "cause", "result"], 0,
    "'Lead to + noun phrase' expresses a consequence.", "cause/effect"),
  E("g-t2-3", "gram-task2-grammar", "Task 2 argument grammar", "gap_fill", 2,
    "The delay was ___ the heavy snow.", ["because", "due to", "since"], 1,
    "'Due to' is followed by a noun phrase ('the heavy snow').", "cause/effect"),
  E("g-t2-4", "gram-task2-grammar", "Task 2 argument grammar", "gap_fill", 2,
    "If public transport improved, fewer people ___ drive.", ["will", "would", "would have"], 1,
    "Second conditional: past in the if-clause, 'would' in the result.", "conditionals"),
  E("g-t2-5", "gram-task2-grammar", "Task 2 argument grammar", "style_choice", 3,
    "Choose the most appropriately hedged claim.", ["This proves that all advertising is harmful.", "This may result in higher costs for consumers.", "This absolutely must cause disaster."], 1,
    "'May result in' limits the claim to possibility.", "hedging"),
  E("g-t2-6", "gram-task2-grammar", "Task 2 argument grammar", "gap_fill", 2,
    "Which modal makes the claim appropriately hedged? 'It ___ be argued that advertising influences children unfairly.'", ["could", "must", "cannot"], 0,
    "'Could be argued' presents the claim as a possible viewpoint rather than a certainty. 'Must be argued' expresses necessity, while 'cannot be argued' expresses impossibility, so neither satisfies the request for hedging.", "hedging"),
  E("g-t2-7", "gram-task2-grammar", "Task 2 argument grammar", "sentence_choice", 2,
    "Choose the parallel thesis statement.", ["This essay will discuss causes, effects and suggest solutions.", "This essay will discuss causes, effects and solutions.", "This essay will discuss causes, effects and to suggest solutions."], 1,
    "All three items are noun phrases, keeping the list parallel.", "parallelism"),
  E("g-t2-8", "gram-task2-grammar", "Task 2 argument grammar", "gap_fill", 2,
    "Drivers ___ pay the congestion charge when entering the city centre; most commuters have switched to the metro as a result.", ["must", "must not", "cannot"], 0,
    "'Must' expresses the obligation; the result clause confirms that drivers do pay, so 'must not' and 'cannot' contradict it.", "modals"),
  E("g-t2-9", "gram-task2-grammar", "Task 2 argument grammar", "gap_fill", 3,
    "The policy, ___ was introduced last year, has reduced congestion.", ["which", "that", "who"], 0,
    "Non-defining relative clauses use 'which' with commas.", "relative clauses"),
  E("g-t2-10", "gram-task2-grammar", "Task 2 argument grammar", "error_identification", 2,
    "Identify the error: 'There are several reasons explain this trend.'", ["missing connector after 'reasons'", "wrong tense", "article error"], 0,
    "A connector is missing: 'There are several reasons that explain this trend' or 'There are several reasons for this trend'.", "complex sentences"),
  E("g-t2-11", "gram-task2-grammar", "Task 2 argument grammar", "gap_fill", 2,
    "Not only ___ traffic increased, but air quality has also worsened.", ["has", "is", "does"], 0,
    "'Not only' at the start triggers inversion with the auxiliary.", "inversion"),
  E("g-t2-12", "gram-task2-grammar", "Task 2 argument grammar", "sentence_choice", 3,
    "Choose the sentence with the best control.", ["The government should invest in education because it benefits both individuals and society.", "Education investment government because benefits society individuals.", "The government should invest in education it benefits society."], 0,
    "The first sentence uses a clear main clause and a controlled reason clause.", "complex sentences"),

  // --- gram-letter-grammar (+8) ---
  E("g-letter-1", "gram-letter-grammar", "General letter grammar", "style_choice", 1,
    "Which request is formal?", ["Can you send me the form?", "I would be grateful if you could send me the form.", "Send me the form, please."], 1,
    "'I would be grateful if you could…' is the formal request pattern.", "register"),
  E("g-letter-2", "gram-letter-grammar", "General letter grammar", "style_choice", 1,
    "Which request is informal?", ["I would appreciate it if you could help.", "Could you possibly help me?", "Can you give me a hand?"], 2,
    "'Can you give me a hand?' is conversational and informal.", "register"),
  E("g-letter-3", "gram-letter-grammar", "General letter grammar", "style_choice", 2,
    "Which apology is semi-formal?", ["I am writing to express my sincere apologies.", "I'm really sorry I missed it.", "I apologise for any inconvenience caused."], 2,
    "'I apologise for any inconvenience caused' suits a semi-formal context.", "register"),
  E("g-letter-4", "gram-letter-grammar", "General letter grammar", "error_identification", 2,
    "Identify the register error: 'I am writing to inform you of the delay. Cheers, mate.'", ["mixed register", "tense", "spelling"], 0,
    "A formal opening should not be paired with an informal closing.", "register"),
  E("g-letter-5", "gram-letter-grammar", "General letter grammar", "gap_fill", 2,
    "___ you tell me where the office is located?", ["Could", "Do", "Are"], 0,
    "'Could you…?' is the polite request form; 'Do you tell me…' and 'Are you tell me…' are ungrammatical.", "modals"),
  E("g-letter-6", "gram-letter-grammar", "General letter grammar", "gap_fill", 2,
    "I ___ be grateful if you could reply by Friday.", ["would", "am", "was"], 0,
    "The polite pattern is 'I would be grateful if…'; 'am be' and 'was be' are ungrammatical.", "modals"),
  E("g-letter-7", "gram-letter-grammar", "General letter grammar", "gap_fill", 2,
    "I look forward to ___ from you.", ["hear", "hearing", "heard"], 1,
    "'Look forward to' takes the gerund.", "gerunds / infinitives"),
  E("g-letter-8", "gram-letter-grammar", "General letter grammar", "gap_fill", 3,
    "___ you need any further information, please do not hesitate to contact me.", ["Should", "Could", "Would"], 0,
    "'Should you need…' is a formal conditional inversion.", "conditionals"),

  // --- gram-punctuation (+6) ---
  E("g-punct-5", "gram-punctuation", "Punctuation", "punctuation", 1,
    "Which correctly joins two independent clauses with a semicolon?", ["The results were clear, the method was flawed.", "The results were clear; the method was flawed.", "The results were clear the method was flawed."], 1,
    "A semicolon (or a full stop or conjunction) correctly joins two closely related independent clauses; a comma alone creates a comma splice.", "punctuation"),
  E("g-punct-6", "gram-punctuation", "Punctuation", "punctuation", 2,
    "Which correctly uses a semicolon before 'however'?", ["In 2020, sales fell, however, profits rose.", "In 2020, sales fell; however, profits rose.", "In 2020, sales fell however profits rose."], 1,
    "A semicolon (or a full stop) is required before 'however' when it joins two clauses.", "punctuation"),
  E("g-punct-7", "gram-punctuation", "Punctuation", "punctuation", 2,
    "Which correctly uses commas to set off a non-restrictive appositive?", ["My brother, an engineer, works abroad.", "My brother an engineer, works abroad.", "My brother, an engineer works abroad."], 0,
    "A non-restrictive appositive ('an engineer') is set off by commas on both sides.", "punctuation"),
  E("g-punct-8", "gram-punctuation", "Punctuation", "punctuation", 2,
    "Which correctly uses an apostrophe for a singular possessor?", ["The government's policy was criticised.", "The governments policy was criticised.", "The governments' policy were criticised."], 0,
    "A singular possessor ('the government') takes an apostrophe before the 's'.", "punctuation"),
  E("g-punct-9", "gram-punctuation", "Punctuation", "punctuation", 3,
    "Which version correctly uses a colon after a complete clause to introduce a list?", ["We visited three cities: Paris, Rome and Vienna.", "We visited three cities, Paris, Rome and Vienna.", "We visited three cities; Paris, Rome and Vienna."], 0,
    "The clause 'We visited three cities' is complete, so a colon can introduce the list that follows. The question specifically asks for correct colon use.", "punctuation"),
  E("g-punct-10", "gram-punctuation", "Punctuation", "punctuation", 3,
    "Which version correctly uses commas to mark a non-essential participial phrase?", ["The survey carried out in June, covered 500 residents.", "The survey, carried out in June, covered 500 residents.", "The survey, carried out in June covered 500 residents."], 1,
    "Two commas — one on each side — set off the non-essential participial phrase 'carried out in June'.", "punctuation"),

  // --- gram-tenses-conditionals (+2) ---
  E("g-tense-6", "gram-tenses-conditionals", "Tense consistency", "gap_fill", 3,
    "By the time the report was published, the situation ______.", ["had already changed", "has already changed", "already changes"], 0,
    "Past perfect marks an action completed before another past event.", "tense"),
  E("g-tense-7", "gram-tenses-conditionals", "Tense consistency", "gap_fill", 3,
    "By next summer, she ______ her thesis.", ["will have completed", "has completed", "had completed"], 0,
    "The future perfect ('will have completed') places the completed action before a future reference point. The present perfect and past perfect do not match the future time frame.", "tense"),

  // --- gram-passive-modals (+4) ---
  E("g-pass-5", "gram-passive-modals", "Passive voice", "gap_fill", 2,
    "The stadium ______ in time for the tournament.", ["has built", "has been built", "is build"], 1,
    "Present perfect passive: 'has been + past participle'; the stadium cannot build itself.", "passive voice"),
  E("g-pass-6", "gram-passive-modals", "Passive voice", "sentence_choice", 3,
    "Where is the passive most appropriate?", ["The researchers carried out the experiment.", "The experiment was carried out under controlled conditions.", "Researchers carry out experiments."], 1,
    "The passive suits a process/method description where the doer is unimportant.", "passive voice"),
  E("g-mod-5", "gram-passive-modals", "Modals", "gap_fill", 2,
    "Students ___ submit the form by Friday; it is compulsory.", ["may", "must", "might"], 1,
    "'Must' expresses obligation; the sentence says it is compulsory.", "modals"),
  E("g-mod-6", "gram-passive-modals", "Modals", "gap_fill", 3,
    "The results ___ be affected by the small sample size, although there is not yet enough evidence to know for certain.", ["might", "must", "can't"], 0,
    "'Might' expresses possibility. The phrase 'not yet enough evidence to know for certain' rules out the certainty of 'must' and 'can't'.", "modals"),
);

export function getGrammarExercises(): GrammarExercise[] {
  return grammarExercises;
}
