// IELTS-oriented grammar practice exercises with explanations.

export interface GrammarExercise {
  id: string;
  topic: string;
  sentence: string;
  // The blank is marked with ___. Correct answer fills it.
  options: string[];
  correct: number;
  explanation: string;
  errorType: string;
}

export const grammarExercises: GrammarExercise[] = [
  {
    id: "g-sv-1",
    topic: "Subject–verb agreement",
    sentence: "The number of people using public transport ___ increased sharply.",
    options: ["have", "has", "are"],
    correct: 1,
    explanation: "'The number of…' takes a singular verb, so 'has' is correct.",
    errorType: "subject-verb agreement",
  },
  {
    id: "g-sv-2",
    topic: "Subject–verb agreement",
    sentence: "A number of students ___ applied for the scholarship.",
    options: ["has", "is", "have"],
    correct: 2,
    explanation: "'A number of…' takes a plural verb, so 'have' is correct.",
    errorType: "subject-verb agreement",
  },
  {
    id: "g-art-1",
    topic: "Articles",
    sentence: "She gave me ___ useful advice about the interview.",
    options: ["a", "an", "—"],
    correct: 2,
    explanation: "'Advice' is uncountable and takes no article.",
    errorType: "articles / countable nouns",
  },
  {
    id: "g-art-2",
    topic: "Articles",
    sentence: "___ information you provided was very helpful.",
    options: ["A", "The", "—"],
    correct: 1,
    explanation: "'The' is used because the information is specific and previously mentioned.",
    errorType: "articles",
  },
  {
    id: "g-tense-1",
    topic: "Tense consistency",
    sentence: "By the time we arrived, the meeting ___.",
    options: ["already started", "has already started", "had already started"],
    correct: 2,
    explanation: "Past perfect ('had started') is used for an action completed before another past action.",
    errorType: "tense",
  },
  {
    id: "g-tense-2",
    topic: "Tense consistency",
    sentence: "Since 2015, the city ___ its public transport network.",
    options: ["expanded", "has expanded", "expands"],
    correct: 1,
    explanation: "'Since + past time' requires the present perfect ('has expanded').",
    errorType: "tense",
  },
  {
    id: "g-modal-1",
    topic: "Modals",
    sentence: "Students ___ wear a uniform, but most choose to.",
    options: ["must", "don't have to", "can't"],
    correct: 1,
    explanation: "'Don't have to' expresses lack of obligation, matching 'but most choose to'.",
    errorType: "modals",
  },
  {
    id: "g-cond-1",
    topic: "Conditionals",
    sentence: "If the government ___ more in education, results would improve.",
    options: ["invests", "invested", "had invested"],
    correct: 1,
    explanation: "Second conditional (unreal present) uses past simple in the if-clause and 'would'.",
    errorType: "conditionals",
  },
  {
    id: "g-cond-2",
    topic: "Conditionals",
    sentence: "If we had left earlier, we ___ the train.",
    options: ["would catch", "would have caught", "will catch"],
    correct: 1,
    explanation: "Third conditional (unreal past) uses 'would have + past participle'.",
    errorType: "conditionals",
  },
  {
    id: "g-passive-1",
    topic: "Passive voice",
    sentence: "The bottles ___ and then transported to the factory.",
    options: ["clean", "are cleaned", "cleaned"],
    correct: 1,
    explanation: "Process descriptions use the passive: 'are cleaned'.",
    errorType: "passive voice",
  },
  {
    id: "g-rel-1",
    topic: "Relative clauses",
    sentence: "The policy, ___ was introduced last year, has reduced waste.",
    options: ["that", "which", "who"],
    correct: 1,
    explanation: "A non-defining relative clause uses 'which' (with commas), not 'that'.",
    errorType: "relative clauses",
  },
  {
    id: "g-noun-1",
    topic: "Noun clauses",
    sentence: "___ the data shows is a clear decline in sales.",
    options: ["That", "What", "Which"],
    correct: 1,
    explanation: "'What' introduces a noun clause as the subject of the sentence.",
    errorType: "noun clauses",
  },
  {
    id: "g-adv-1",
    topic: "Adverbial clauses",
    sentence: "___ demand rose, prices increased sharply.",
    options: ["Because", "Although", "Despite"],
    correct: 0,
    explanation: "'Because' introduces a cause-effect relationship between the clauses.",
    errorType: "adverbial clauses",
  },
  {
    id: "g-ger-1",
    topic: "Gerunds / infinitives",
    sentence: "Many people enjoy ___ in their free time.",
    options: ["to travel", "travel", "travelling"],
    correct: 2,
    explanation: "'Enjoy' is followed by a gerund ('travelling').",
    errorType: "gerunds/infinitives",
  },
  {
    id: "g-comp-1",
    topic: "Comparatives",
    sentence: "This is ___ interesting book I have ever read.",
    options: ["the most", "more", "most"],
    correct: 0,
    explanation: "Superlative with 'the most' is used for three or more items.",
    errorType: "comparatives/superlatives",
  },
  {
    id: "g-prep-1",
    topic: "Prepositions",
    sentence: "The course focuses ___ developing practical skills.",
    options: ["in", "on", "at"],
    correct: 1,
    explanation: "'Focus on' is the correct collocation.",
    errorType: "prepositions",
  },
  {
    id: "g-conj-1",
    topic: "Conjunctions",
    sentence: "The project was difficult; ___, the team completed it on time.",
    options: ["however", "therefore", "because"],
    correct: 0,
    explanation: "'However' contrasts the difficulty with the successful completion.",
    errorType: "conjunctions",
  },
  {
    id: "g-punc-1",
    topic: "Punctuation",
    sentence: "We need to buy three things___ bread, milk and eggs.",
    options: [":", ";", ","],
    correct: 0,
    explanation: "A colon introduces a list.",
    errorType: "punctuation",
  },
  {
    id: "g-par-1",
    topic: "Parallelism",
    sentence: "The job involves planning, organising and ___ reports.",
    options: ["write", "writing", "to write"],
    correct: 1,
    explanation: "Parallel structure requires matching gerunds: planning, organising, writing.",
    errorType: "parallelism",
  },
  {
    id: "g-frag-1",
    topic: "Fragments",
    sentence: "Which sentence is complete?",
    options: ["Because the cost was too high.", "The project was cancelled because the cost was too high.", "Although the cost was too high."],
    correct: 1,
    explanation: "Only the middle option has a complete independent clause.",
    errorType: "fragments",
  },
  {
    id: "g-runon-1",
    topic: "Run-on sentences",
    sentence: "Which sentence is punctuated correctly?",
    options: ["The test was hard, we still passed.", "The test was hard; however, we still passed.", "The test was hard we still passed."],
    correct: 1,
    explanation: "A semicolon (or full stop) correctly joins the two independent clauses.",
    errorType: "run-on sentences",
  },
  {
    id: "g-formal-1",
    topic: "Formal academic style",
    sentence: "Which is the most formal?",
    options: ["The government decided to cut taxes.", "The government's decision to cut taxes was widely debated.", "They decided to cut taxes, you know."],
    correct: 1,
    explanation: "Nominalisation ('the government's decision') is a feature of formal academic style.",
    errorType: "formal style / nominalisation",
  },
  {
    id: "g-hedge-1",
    topic: "Hedging",
    sentence: "Which sentence uses appropriate hedging?",
    options: ["This proves that all students fail.", "This may result in higher costs.", "This absolutely must cause a disaster."],
    correct: 1,
    explanation: "'May result in' is appropriately cautious; the others overstate.",
    errorType: "hedging",
  },
  {
    id: "g-sv-3",
    topic: "Subject–verb agreement",
    sentence: "Neither the manager nor the employees ___ aware of the change.",
    options: ["was", "were", "is"],
    correct: 1,
    explanation: "With 'neither…nor', the verb agrees with the nearer subject ('the employees' → plural).",
    errorType: "subject-verb agreement",
  },
  {
    id: "g-art-3",
    topic: "Articles",
    sentence: "He plays ___ important role in the community.",
    options: ["a", "an", "the"],
    correct: 1,
    explanation: "'An' precedes a vowel sound ('important').",
    errorType: "articles",
  },
  {
    id: "g-tense-3",
    topic: "Tense consistency",
    sentence: "She ___ in London since 2019.",
    options: ["lives", "has lived", "lived"],
    correct: 1,
    explanation: "Present perfect ('has lived') is used with 'since' for an action continuing to now.",
    errorType: "tense",
  },
  {
    id: "g-cond-3",
    topic: "Conditionals",
    sentence: "If I had studied harder, I ___ the exam.",
    options: ["would pass", "would have passed", "will pass"],
    correct: 1,
    explanation: "Third conditional: past perfect in the if-clause, 'would have + past participle' in the main clause.",
    errorType: "conditionals",
  },
  {
    id: "g-rel-2",
    topic: "Relative clauses",
    sentence: "The chart, ___ shows export data, was published last year.",
    options: ["which", "that", "who"],
    correct: 0,
    explanation: "Non-defining relative clauses use 'which' (with commas), never 'that'.",
    errorType: "relative clauses",
  },
  {
    id: "g-pass-2",
    topic: "Passive voice",
    sentence: "The results ___ by the researchers next week.",
    options: ["will publish", "will be published", "are publishing"],
    correct: 1,
    explanation: "Future passive: 'will be + past participle'.",
    errorType: "passive voice",
  },
  {
    id: "g-comp-2",
    topic: "Comparatives",
    sentence: "The more you practise, ___ your accuracy becomes.",
    options: ["the better", "better", "the best"],
    correct: 0,
    explanation: "'The more…, the better…' is a double comparative structure.",
    errorType: "comparatives",
  },
  {
    id: "g-modal-2",
    topic: "Modals",
    sentence: "You ___ submit the form by Friday, but it is not compulsory.",
    options: ["must", "may", "cannot"],
    correct: 1,
    explanation: "'May' expresses permission/possibility without obligation; 'must' would make it compulsory.",
    errorType: "modals",
  },
  {
    id: "g-parallel-2",
    topic: "Parallelism",
    sentence: "The course teaches reading, writing, and how to speak clearly.",
    options: ["and speaking clearly", "and to speak clearly", "no change"],
    correct: 0,
    explanation: "Parallel structure: 'reading, writing, and speaking clearly' keeps the gerund form consistent.",
    errorType: "parallelism",
  },
  {
    id: "g-ref-1",
    topic: "Reference words",
    sentence: "Many cities have expanded rapidly. ___ has increased traffic congestion.",
    options: ["This", "They", "It is"],
    correct: 0,
    explanation: "'This' refers back to the whole previous idea, a common cohesive device.",
    errorType: "reference / cohesion",
  },
  {
    id: "g-count-1",
    topic: "Countability",
    sentence: "The report contains ___ evidence to support the claim.",
    options: ["many", "much", "a few"],
    correct: 1,
    explanation: "'Evidence' is uncountable, so 'much' is correct.",
    errorType: "countability",
  },
  {
    id: "g-prep-2",
    topic: "Prepositions",
    sentence: "The government is concerned ___ rising pollution levels.",
    options: ["about", "for", "on"],
    correct: 0,
    explanation: "'Concerned about' is the standard collocation.",
    errorType: "prepositions / collocation",
  },
  {
    id: "g-frag-2",
    topic: "Fragments",
    sentence: "Which is a complete sentence?",
    options: ["Although the economy grew slowly.", "Because of the new policy.", "The policy reduced unemployment."],
    correct: 2,
    explanation: "Only the third has a subject and a main verb; the others are dependent clauses.",
    errorType: "sentence fragments",
  },
  {
    id: "g-runon-2",
    topic: "Run-on sentences",
    sentence: "Which fixes the run-on: 'Traffic increased, the city built new roads'?",
    options: ["Traffic increased, so the city built new roads.", "Traffic increased the city built new roads.", "no change"],
    correct: 0,
    explanation: "A coordinating conjunction ('so') or a semicolon is needed between two independent clauses.",
    errorType: "run-on sentences",
  },
  {
    id: "g-punct-2",
    topic: "Punctuation",
    sentence: "Choose the correct punctuation.",
    options: ["The test is difficult, however, students pass it.", "The test is difficult; however, students pass it.", "The test is difficult however students pass it."],
    correct: 1,
    explanation: "A semicolon (or a full stop) is required before 'however' when it joins two clauses.",
    errorType: "punctuation",
  },
  {
    id: "g-noun-2",
    topic: "Noun clauses",
    sentence: "___ the economy will recover is uncertain.",
    options: ["That", "Whether", "Because"],
    correct: 1,
    explanation: "'Whether' introduces a noun clause expressing an indirect yes/no question.",
    errorType: "noun clauses",
  },
  {
    id: "g-ger-2",
    topic: "Gerunds / infinitives",
    sentence: "Many students avoid ___ before the exam.",
    options: ["to study", "studying", "study"],
    correct: 1,
    explanation: "'Avoid' is followed by a gerund ('avoid studying').",
    errorType: "gerunds / infinitives",
  },
  {
    id: "g-adv-2",
    topic: "Adverbial clauses",
    sentence: "___ the price rose, demand remained stable.",
    options: ["Although", "Because", "So"],
    correct: 0,
    explanation: "'Although' introduces a contrast, which matches the unexpected stability of demand.",
    errorType: "adverbial clauses / contrast",
  },
  {
    id: "g-conj-2",
    topic: "Conjunctions",
    sentence: "The plan was popular ___ it was expensive.",
    options: ["and", "even though", "therefore"],
    correct: 1,
    explanation: "'Even though' links the positive and negative ideas with contrast.",
    errorType: "conjunctions",
  },
  {
    id: "g-cohesion-1",
    topic: "Cohesion",
    sentence: "Choose the most cohesive link: 'Air pollution has risen. ___, more people cycle to work.'",
    options: ["Consequently", "Moreover", "For example"],
    correct: 0,
    explanation: "'Consequently' shows the result of the first sentence, linking the ideas.",
    errorType: "cohesion / linking devices",
  },
  {
    id: "g-complex-1",
    topic: "Complex clauses",
    sentence: "Combine: 'The policy was expensive. It was still introduced.'",
    options: ["Although the policy was expensive, it was still introduced.", "The policy was expensive it was still introduced.", "The policy was expensive, but introduced it was."],
    correct: 0,
    explanation: "A subordinate clause with 'although' creates a correct complex sentence.",
    errorType: "complex sentences",
  },
  {
    id: "g-boundary-1",
    topic: "Sentence boundaries",
    sentence: "Which is punctuated correctly?",
    options: ["Many people work remotely. This saves time and money.", "Many people work remotely, this saves time and money.", "Many people work remotely this saves time and money."],
    correct: 0,
    explanation: "Two independent clauses need a full stop, semicolon or conjunction — not a comma alone.",
    errorType: "sentence boundaries",
  },
  {
    id: "g-np-1",
    topic: "Noun phrases",
    sentence: "___ of urban housing is a major policy challenge.",
    options: ["The rapid rising cost", "The rapidly rising cost", "The rapid rise cost"],
    correct: 1,
    explanation: "Adverb 'rapidly' modifies the participle 'rising' inside the noun phrase.",
    errorType: "noun phrases",
  },
  {
    id: "g-sv-4",
    topic: "Subject–verb agreement",
    sentence: "Every one of the students ___ required to attend.",
    options: ["are", "is", "were"],
    correct: 1,
    explanation: "'Every one' is singular, so the verb is 'is'.",
    errorType: "subject-verb agreement",
  },
  {
    id: "g-art-4",
    topic: "Articles",
    sentence: "She is ___ only person who knows the answer.",
    options: ["a", "the", "—"],
    correct: 1,
    explanation: "'The' is used with 'only' to mark uniqueness.",
    errorType: "articles",
  },
  {
    id: "g-tense-4",
    topic: "Tense consistency",
    sentence: "By 2030, the city ___ its population double.",
    options: ["will see", "will have seen", "sees"],
    correct: 1,
    explanation: "Future perfect ('will have seen') is used for an action completed before a future point.",
    errorType: "tense",
  },
  {
    id: "g-cond-4",
    topic: "Conditionals",
    sentence: "If the government invests in railways, traffic congestion ___.",
    options: ["will decrease", "would decrease", "would have decreased"],
    correct: 0,
    explanation: "First conditional (real possibility): present in the if-clause, 'will' in the result.",
    errorType: "conditionals",
  },
  {
    id: "g-rel-3",
    topic: "Relative clauses",
    sentence: "The city ___ I grew up has changed a lot.",
    options: ["where", "which", "that"],
    correct: 0,
    explanation: "'Where' is the relative adverb for place.",
    errorType: "relative clauses",
  },
  {
    id: "g-pass-3",
    topic: "Passive voice",
    sentence: "Which is the correct passive?",
    options: ["A new hospital has built.", "A new hospital has been built.", "A new hospital is build."],
    correct: 1,
    explanation: "Present perfect passive: 'has been + past participle'.",
    errorType: "passive voice",
  },
  {
    id: "g-comp-3",
    topic: "Comparatives",
    sentence: "Public transport is ___ than driving in most cities.",
    options: ["more cheap", "cheaper", "more cheaper"],
    correct: 1,
    explanation: "'Cheap' is a one-syllable adjective, so the comparative is 'cheaper'.",
    errorType: "comparatives",
  },
  {
    id: "g-modal-3",
    topic: "Modals",
    sentence: "Students ___ wear a uniform; it is optional.",
    options: ["must", "have to", "can"],
    correct: 2,
    explanation: "'Can' expresses permission without obligation, matching 'optional'.",
    errorType: "modals",
  },
  {
    id: "g-hedge-3",
    topic: "Hedging",
    sentence: "Which is the most appropriately hedged claim?",
    options: ["Technology definitely destroys all jobs.", "Technology tends to reduce certain types of routine work.", "Technology ruins everything."],
    correct: 1,
    explanation: "'Tends to' and 'certain types' make the claim appropriately cautious.",
    errorType: "hedging",
  },
  {
    id: "g-count-2",
    topic: "Countability",
    sentence: "The research provides ___ useful information.",
    options: ["many", "a number of", "a great deal of"],
    correct: 2,
    explanation: "'Information' is uncountable; 'a great deal of' is used with uncountables.",
    errorType: "countability",
  },
  {
    id: "g-prep-3",
    topic: "Prepositions",
    sentence: "There has been a rise ___ the number of electric cars.",
    options: ["of", "in", "on"],
    correct: 1,
    explanation: "The standard collocation is 'a rise in'.",
    errorType: "prepositions / collocation",
  },
  {
    id: "g-parallel-3",
    topic: "Parallelism",
    sentence: "Choose the parallel version.",
    options: ["The essay discusses causes, effects, and to suggest solutions.", "The essay discusses causes, effects, and solutions.", "The essay discusses causes, effects and suggesting solutions."],
    correct: 1,
    explanation: "All three items are noun phrases, keeping the list parallel.",
    errorType: "parallelism",
  },
  {
    id: "g-ref-2",
    topic: "Reference words",
    sentence: "Governments should invest in education. ___ brings long-term benefits.",
    options: ["This", "They", "It is"],
    correct: 0,
    explanation: "'This' refers back to the whole idea of investing in education.",
    errorType: "reference / cohesion",
  },
  {
    id: "g-formal-2",
    topic: "Formal academic style",
    sentence: "Which is most appropriate for academic writing?",
    options: ["Kids watch too much TV, and it's bad.", "Children's excessive television viewing has been linked to negative outcomes.", "Watching TV a lot is really bad for children."],
    correct: 1,
    explanation: "Nominalisation and precise vocabulary mark formal academic style.",
    errorType: "formal style",
  },
  {
    id: "g-punct-3",
    topic: "Punctuation",
    sentence: "Choose the correct list punctuation.",
    options: ["The course covers reading writing and listening.", "The course covers reading, writing, and listening.", "The course covers, reading, writing, and listening."],
    correct: 1,
    explanation: "Commas separate the three items in the series.",
    errorType: "punctuation",
  },
];

export function getGrammarExercises(): GrammarExercise[] {
  return grammarExercises;
}
