// IELTS-oriented grammar practice exercises with explanations.

export interface GrammarExercise {
  id: string;
  topic: string;
  sentence: string;
  // The blank is marked with ___. Correct answer fills it.
  options: string[];
  correct: number;
  explanation: string;
  errorType: string;
}

export const grammarExercises: GrammarExercise[] = [
  {
    id: "g-sv-1",
    topic: "Subject–verb agreement",
    sentence: "The number of people using public transport ___ increased sharply.",
    options: ["have", "has", "are"],
    correct: 1,
    explanation: "'The number of…' takes a singular verb, so 'has' is correct.",
    errorType: "subject-verb agreement",
  },
  {
    id: "g-sv-2",
    topic: "Subject–verb agreement",
    sentence: "A number of students ___ applied for the scholarship.",
    options: ["has", "is", "have"],
    correct: 2,
    explanation: "'A number of…' takes a plural verb, so 'have' is correct.",
    errorType: "subject-verb agreement",
  },
  {
    id: "g-art-1",
    topic: "Articles",
    sentence: "She gave me ___ useful advice about the interview.",
    options: ["a", "an", "—"],
    correct: 2,
    explanation: "'Advice' is uncountable and takes no article.",
    errorType: "articles / countable nouns",
  },
  {
    id: "g-art-2",
    topic: "Articles",
    sentence: "___ information you provided was very helpful.",
    options: ["A", "The", "—"],
    correct: 1,
    explanation: "'The' is used because the information is specific and previously mentioned.",
    errorType: "articles",
  },
  {
    id: "g-tense-1",
    topic: "Tense consistency",
    sentence: "By the time we arrived, the meeting ___.",
    options: ["already started", "has already started", "had already started"],
    correct: 2,
    explanation: "Past perfect ('had started') is used for an action completed before another past action.",
    errorType: "tense",
  },
  {
    id: "g-tense-2",
    topic: "Tense consistency",
    sentence: "Since 2015, the city ___ its public transport network.",
    options: ["expanded", "has expanded", "expands"],
    correct: 1,
    explanation: "'Since + past time' requires the present perfect ('has expanded').",
    errorType: "tense",
  },
  {
    id: "g-modal-1",
    topic: "Modals",
    sentence: "Students ___ wear a uniform, but most choose to.",
    options: ["must", "don't have to", "can't"],
    correct: 1,
    explanation: "'Don't have to' expresses lack of obligation, matching 'but most choose to'.",
    errorType: "modals",
  },
  {
    id: "g-cond-1",
    topic: "Conditionals",
    sentence: "If the government ___ more in education, results would improve.",
    options: ["invests", "invested", "had invested"],
    correct: 1,
    explanation: "Second conditional (unreal present) uses past simple in the if-clause and 'would'.",
    errorType: "conditionals",
  },
  {
    id: "g-cond-2",
    topic: "Conditionals",
    sentence: "If we had left earlier, we ___ the train.",
    options: ["would catch", "would have caught", "will catch"],
    correct: 1,
    explanation: "Third conditional (unreal past) uses 'would have + past participle'.",
    errorType: "conditionals",
  },
  {
    id: "g-passive-1",
    topic: "Passive voice",
    sentence: "The bottles ___ and then transported to the factory.",
    options: ["clean", "are cleaned", "cleaned"],
    correct: 1,
    explanation: "Process descriptions use the passive: 'are cleaned'.",
    errorType: "passive voice",
  },
  {
    id: "g-rel-1",
    topic: "Relative clauses",
    sentence: "The policy, ___ was introduced last year, has reduced waste.",
    options: ["that", "which", "who"],
    correct: 1,
    explanation: "A non-defining relative clause uses 'which' (with commas), not 'that'.",
    errorType: "relative clauses",
  },
  {
    id: "g-noun-1",
    topic: "Noun clauses",
    sentence: "___ the data shows is a clear decline in sales.",
    options: ["That", "What", "Which"],
    correct: 1,
    explanation: "'What' introduces a noun clause as the subject of the sentence.",
    errorType: "noun clauses",
  },
  {
    id: "g-adv-1",
    topic: "Adverbial clauses",
    sentence: "___ demand rose, prices increased sharply.",
    options: ["Because", "Although", "Despite"],
    correct: 0,
    explanation: "'Because' introduces a cause-effect relationship between the clauses.",
    errorType: "adverbial clauses",
  },
  {
    id: "g-ger-1",
    topic: "Gerunds / infinitives",
    sentence: "Many people enjoy ___ in their free time.",
    options: ["to travel", "travel", "travelling"],
    correct: 2,
    explanation: "'Enjoy' is followed by a gerund ('travelling').",
    errorType: "gerunds/infinitives",
  },
  {
    id: "g-comp-1",
    topic: "Comparatives",
    sentence: "This is ___ interesting book I have ever read.",
    options: ["the most", "more", "most"],
    correct: 0,
    explanation: "Superlative with 'the most' is used for three or more items.",
    errorType: "comparatives/superlatives",
  },
  {
    id: "g-prep-1",
    topic: "Prepositions",
    sentence: "The course focuses ___ developing practical skills.",
    options: ["in", "on", "at"],
    correct: 1,
    explanation: "'Focus on' is the correct collocation.",
    errorType: "prepositions",
  },
  {
    id: "g-conj-1",
    topic: "Conjunctions",
    sentence: "The project was difficult; ___, the team completed it on time.",
    options: ["however", "therefore", "because"],
    correct: 0,
    explanation: "'However' contrasts the difficulty with the successful completion.",
    errorType: "conjunctions",
  },
  {
    id: "g-punc-1",
    topic: "Punctuation",
    sentence: "We need to buy three things___ bread, milk and eggs.",
    options: [":", ";", ","],
    correct: 0,
    explanation: "A colon introduces a list.",
    errorType: "punctuation",
  },
  {
    id: "g-par-1",
    topic: "Parallelism",
    sentence: "The job involves planning, organising and ___ reports.",
    options: ["write", "writing", "to write"],
    correct: 1,
    explanation: "Parallel structure requires matching gerunds: planning, organising, writing.",
    errorType: "parallelism",
  },
  {
    id: "g-frag-1",
    topic: "Fragments",
    sentence: "Which sentence is complete?",
    options: ["Because the cost was too high.", "The project was cancelled because the cost was too high.", "Although the cost was too high."],
    correct: 1,
    explanation: "Only the middle option has a complete independent clause.",
    errorType: "fragments",
  },
  {
    id: "g-runon-1",
    topic: "Run-on sentences",
    sentence: "Which sentence is punctuated correctly?",
    options: ["The test was hard, we still passed.", "The test was hard; however, we still passed.", "The test was hard we still passed."],
    correct: 1,
    explanation: "A semicolon (or full stop) correctly joins the two independent clauses.",
    errorType: "run-on sentences",
  },
  {
    id: "g-formal-1",
    topic: "Formal academic style",
    sentence: "Which is the most formal?",
    options: ["The government decided to cut taxes.", "The government's decision to cut taxes was widely debated.", "They decided to cut taxes, you know."],
    correct: 1,
    explanation: "Nominalisation ('the government's decision') is a feature of formal academic style.",
    errorType: "formal style / nominalisation",
  },
  {
    id: "g-hedge-1",
    topic: "Hedging",
    sentence: "Which sentence uses appropriate hedging?",
    options: ["This proves that all students fail.", "This may result in higher costs.", "This absolutely must cause a disaster."],
    correct: 1,
    explanation: "'May result in' is appropriately cautious; the others overstate.",
    errorType: "hedging",
  },
];

export function getGrammarExercises(): GrammarExercise[] {
  return grammarExercises;
}
